### ISSUE TITLE
No module named 'timm' with Comfyui Windows Portable

### ISSUE THREAD

**Issue by WSJUSA** [Fannovel16/comfyui_controlnet_aux#1]
Modules are not loading in startup due to timm library missing

[comfyui_controlnet_aux] | INFO -> Some nodes failed to load:
        Failed to import module bae because ModuleNotFoundError: No module named 'timm'
        Failed to import module hed because ModuleNotFoundError: No module named 'timm'
        Failed to import module leres because ModuleNotFoundError: No module named 'timm'
        Failed to import module lineart because ModuleNotFoundError: No module named 'timm'
        Failed to import module lineart_anime because ModuleNotFoundError: No module named 'timm'
        Failed to import module manga_line because ModuleNotFoundError: No module named 'timm'
        Failed to import module midas because ModuleNotFoundError: No module named 'timm'
        Failed to import module mlsd because ModuleNotFoundError: No module named 'timm'
        Failed to import module openpose because ModuleNotFoundError: No module named 'timm'
        Failed to import module pidinet because ModuleNotFoundError: No module named 'timm'
        Failed to import module scribble because ModuleNotFoundError: No module named 'timm'
        Failed to import module simple_cv2 because ModuleNotFoundError: No module named 'timm'
        Failed to import module zoe because ModuleNotFoundError: No module named 'timm'

Check that you properly installed the dependencies.

--

Also tried the install.bat, it through an error on the timm reference in requirements.txt

ERROR: Invalid requirement: 'timm==0.6.13 #https://github.com/isl-org/MiDaS/issues/215#issuecomment-1554468063'

**Comment by Fannovel16** [comment]
Fixed at https://github.com/Fannovel16/comfyui_controlnet_aux/commit/25adaeff2af8874833a608999aa549213a109ccf
