### ISSUE TITLE
Problems in ComfyUI when trying to use the Zoe-Depthmap preprocessor. Problem when using SD 1.5 and SDXL models. Below is a screenshot of the error.

### ISSUE THREAD

**Issue by Speach1sdef178** [Fannovel16/comfyui_controlnet_aux#103]
![ZOE-DepthMapPreprocessor_error](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/150073057/1a33090e-8d52-4349-b594-7584f5b0348a)

**Comment by Speach1sdef178** [comment]
Problems in ComfyUI when trying to use the Zoe-Depthmap preprocessor. Problem when using SD 1.5 and SDXL models. Below is a screenshot of the error. Version ComfyUI and all modules updated today

**Comment by Fannovel16** [comment]
@Speach1sdef178 I embeded timm 0.6.13. Can you test the latest commit?

**Comment by Speach1sdef178** [comment]
of course, I will definitely try, I will unsubscribe about the result. I didn't see your message earlier, it's already late at night. I'll check tomorrow night. Thank you.

**Comment by Speach1sdef178** [comment]
Couldn't resist and checked. Thank you so much, your fix fixed the problem. Everything is working fine now.

**Comment by Speach1sdef178** [comment]
Thank you so much, your fix fixed the problem. Everything is working fine now.
