### ISSUE TITLE
DWPose might run very slowly

### ISSUE THREAD

**Issue by ekka007** [Fannovel16/comfyui_controlnet_aux#110]
UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")

**Comment by DmytroSokhach** [comment]
I think it is duplicate of  "Onnxruntime not found or doesn't come with acceleration providers" #75

**Comment by Fannovel16** [comment]
@ekka007 Close this to avoid duplication. You can post your issue at https://github.com/Fannovel16/comfyui_controlnet_aux/issues/75
