### ISSUE TITLE
Does Canny have a balance mode, otherwise the generated graph will have lines or dots

### ISSUE THREAD

**Issue by starinskycc** [Fannovel16/comfyui_controlnet_aux#111]
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/6244330/c297ce6c-54ff-43b0-93b4-e8d0bc81bcc7)

**Comment by starinskycc** [comment]
like this 
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/6244330/345d0a6e-fea7-46ae-9b75-620351c68323)

**Comment by Fannovel16** [comment]
@starinskycc Balance is the default mode in Comfy while "My prompt is more impotant" == Scaled Soft Controlnet Weights with default weight 0.825
