### ISSUE TITLE
 set local_dir_use_symlinks=True,  this is optimal in term of disk usage

### ISSUE THREAD

**Issue by xingren23** [Fannovel16/comfyui_controlnet_aux#113]
when set local_dir_use_symlinks=True, hf_hub_download download file in the cache path, and link to current path
if so , multi comfyui env could share the model path, this is optimal in term of disk usage.

    If `local_dir` is provided, the file structure from the repo will be replicated in this location. You can configure
    how you want to move those files:
      - If `local_dir_use_symlinks="auto"` (default), files are downloaded and stored in the cache directory as blob
        files. Small files (<5MB) are duplicated in `local_dir` while a symlink is created for bigger files. The goal
        is to be able to manually edit and save small files without corrupting the cache while saving disk space for
        binary files. The 5MB threshold can be configured with the `HF_HUB_LOCAL_DIR_AUTO_SYMLINK_THRESHOLD`
        environment variable.
      - If `local_dir_use_symlinks=True`, files are downloaded, stored in the cache directory and symlinked in `local_dir`.
        This is optimal in term of disk usage but files must not be manually edited.
      - If `local_dir_use_symlinks=False` and the blob files exist in the cache directory, they are duplicated in the
        local dir. This means disk usage is not optimized.
      - Finally, if `local_dir_use_symlinks=False` and the blob files do not exist in the cache directory, then the
        files are downloaded and directly placed under `local_dir`. This means if you need to download them again later,
        they will be re-downloaded entirely.

**Comment by Fannovel16** [comment]
I remembered now. symlink on Windows suck lol

**Comment by Layer-norm** [comment]
Not a good idea, the windows default huggingface cache floder on system drive which may not have enogh space for models. Please give  me some time, I would like to try some other way to achieve this.

**Comment by xingren23** [comment]
> Not a good idea, the windows default huggingface cache floder on system drive which may not have enogh space for models. Please give me some time, I would like to try some other way to achieve this.

user could modify default cache dir with env var: 
HUGGINGFACE_HUB_CACHE = os.getenv("HUGGINGFACE_HUB_CACHE", default_cache_path)

**Comment by xingren23** [comment]
> Not a good idea, the windows default huggingface cache floder on system drive which may not have enogh space for models. Please give me some time, I would like to try some other way to achieve this.

user could modify default cache dir with env var: 
HUGGINGFACE_HUB_CACHE = os.getenv("HUGGINGFACE_HUB_CACHE", default_cache_path)

**Comment by Layer-norm** [comment]
I know it, but I can't package these models to ckpts.zip if I use symlinks.

**Comment by xingren23** [comment]
I believe it might not be necessary to package these models

**Comment by Layer-norm** [comment]
It is VERY important in CHINA. Many pepople even don't know what is Administrator permissions, and have problem in download. And I will try to use symlinks by default, but if any error occur It should download all the stuff into ckpts folder as before.
