### ISSUE TITLE
Error occurred when executing FakeScribblePreprocessor:

### ISSUE THREAD

**Issue by alexbofa** [Fannovel16/comfyui_controlnet_aux#12]
Hello, I have problem with only **Fake Scribble Lines (aka scribble_hed)** node. [comfy_controlnet_preprocessors](https://github.com/Fannovel16/comfy_controlnet_preprocessors) is deleted, everything is updated
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/58225118/5a4d430d-f275-43c4-b964-487d8f6976f9)

in console
```bat
got prompt
!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\hed.py", line 43, in execute
    model = HEDdetector.from_pretrained(HF_MODEL_NAME, cache_dir=annotator_ckpts_path).to(model_management.get_torch_device())
NameError: name 'HEDdetector' is not defined

Prompt executed in 0.03 seconds
```

**Comment by discovermodo** [comment]
I got this working by adding "from controlnet_aux.hed import HEDdetector" to node_wrappers/hed.py
Add it after line 42

**Comment by cdsama** [comment]
add `from controlnet_aux.hed import HEDdetector`
before the error line.

**Comment by Fannovel16** [comment]
Fixed at https://github.com/Fannovel16/comfyui_controlnet_aux/pull/17/files

**Comment by alexbofa** [comment]
Thanks, it's work 🖤
