### ISSUE TITLE
Requested help, About the animal POSE NODE.....

### ISSUE THREAD

**Issue by aimarxjg** [Fannovel16/comfyui_controlnet_aux#127]
Please help me, am I connecting nodes correctly? It seems that the result is completely wrong, maybe I connected incorrectly or some key node is missing?
![31123194255](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/132532636/3eb8a293-08da-4f77-ac2a-ae1621b5d26a)

**Comment by Fannovel16** [comment]
@aimarxjg This preprocessor is only compatiable with [AnimalPose ControlNet](https://github.com/abehonest/ControlNet_AnimalPose/). You can download it at https://drive.google.com/file/d/1Q0lvCVFx2hGlgI7Q-npJKDFqZRwZltYY/view
