### ISSUE TITLE
DensePose Estimation always gives the sample solution

### ISSUE THREAD

**Issue by jav12z** [Fannovel16/comfyui_controlnet_aux#139]
It doesn't matter the picture I give to it, it always gives me the map shown as an example in the instructions of the webpage.

![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/110166549/50ee0d75-c744-48e5-a37e-a0afa37803ed)

**Comment by alexfredo** [comment]
Same problem

**Comment by liuslLSL** [comment]
Same problem +1
![QAL_M2%)3EOO{%{IK$S(903](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/131424613/8825db3b-fc99-4392-b0aa-68bcb261f99d)

**Comment by botnang** [comment]
Same problem +1

![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/32015065/0202db65-24f9-4619-b063-662d45d2678c)

**Comment by Fannovel16** [comment]
Fixed in https://github.com/Fannovel16/comfyui_controlnet_aux/pull/144
