### ISSUE TITLE
Error occurred when executing LineArtPreprocessor

### ISSUE THREAD

**Issue by sudo15** [Fannovel16/comfyui_controlnet_aux#140]
Getting this issue while doing vid2vid animation in comfyui 
![prblm](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/142871589/52d474fa-9033-45f6-b818-5c7720fd8aeb)
Do need some help!

**Comment by Layer-norm** [comment]
- Delete cache folder `D:\\ComfyUI_windows_portable_nvidia_cu118_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\ckpts\\lllyasviel\\Annotators\\cache` and **restart comfyui**.
 - Or download [sk_model.pth](https://huggingface.co/lllyasviel/Annotators/resolve/main/sk_model.pth)and[sk_model2.pth](https://huggingface.co/lllyasviel/Annotators/blob/main/sk_model2.pth) into `D:\\ComfyUI_windows_portable_nvidia_cu118_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\ckpts\\lllyasviel\\Annotators\\` folder

**Comment by flyingrtx2333** [comment]
I also had the same issue. I first tried to manually download the .pth file and move it to the (my directory )\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\lllyasviel folder, but it didn't work for me. I think the reason is that the absolute path is too long in Windows 11, so I tried to rename the absolute directory path from D:\xxx\xxx\xxx\comfyUI to D:\ComfyUI to make it shorter. After restarting ComfyUI, it worked for me!
![H 2RGG ONQGQGG7CDK6}~YG](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/127621846/8a08d423-a685-4b43-b7c7-ffde623409ed)

**Comment by codewithubaid** [comment]
how 

> I also had the same issue. I first tried to manually download the .pth file and move it to the (my directory )\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\lllyasviel folder, but it didn't work for me. I think the reason is that the absolute path is too long in Windows 11, so I tried to rename the absolute directory path from D:\xxx\xxx\xxx\comfyUI to D:\ComfyUI to make it shorter. After restarting ComfyUI, it worked for me! ![H 2RGG ONQGQGG7CDK6}~YG](https://private-user-images.githubusercontent.com/127621846/335772879-8a08d423-a685-4b43-b7c7-ffde623409ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNDM2NzIsIm5iZiI6MTcyNjM0MzM3MiwicGF0aCI6Ii8xMjc2MjE4NDYvMzM1NzcyODc5LThhMDhkNDIzLWE2ODUtNGI0My1iN2M3LWZmZGU2MjM0MDllZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNFQxOTQ5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjU4MGI5NGIwNjUxM2YwMWYwNmFjYzk2NDM4ZjE2MWM4ZWIyM2RjYTI0ZjEwYmU1ZWE0MmNhZjY3NGQ4NjljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ws-E7Pm6bXqBhlaynk3-KsEvh7eI7C0DiE2Msp8BmA0)

how to change path?
