### ISSUE TITLE
DensePose: TypeError: common_annotator_call() missing 1 required positional argument: 'tensor_image'

### ISSUE THREAD

**Issue by botnang** [Fannovel16/comfyui_controlnet_aux#145]
Thank you for your hard work. I have upgraded to the latest version, densepose still cannot run correctly, the error message is as follows:

`got prompt
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\AI\ComfyUI-Latest\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\AI\ComfyUI-Latest\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\AI\ComfyUI-Latest\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\AI\ComfyUI-Latest\custom_nodes\comfyui_controlnet_aux\node_wrappers\densepose.py", line 22, in execute
    return (common_annotator_call(image, cmap="viridis" if "Viridis" in cmap else "parula", resolution=resolution), )
TypeError: common_annotator_call() missing 1 required positional argument: 'tensor_image'

Prompt executed in 0.46 seconds`

![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/32015065/c3688cb9-339d-49c8-873d-4bd21f607f92)

**Comment by Fannovel16** [comment]
It should work now
