### ISSUE TITLE
which processor can be used by "control_v11p_sd15_softedge“

### ISSUE THREAD

**Issue by starinskycc** [Fannovel16/comfyui_controlnet_aux#149]
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/6244330/2334eda9-2054-43c9-b581-6426b215fc46)

**Comment by Fannovel16** [comment]
Refer to https://github.com/Fannovel16/comfyui_controlnet_aux?tab=readme-ov-file#nodes-sections-are-categories-in-comfy-menu for other preprocessors
