### ISSUE TITLE
dwpose place the arm behind the body

### ISSUE THREAD

**Issue by GoodGoodstudy0daydayup** [Fannovel16/comfyui_controlnet_aux#150]
In the skeleton diagram generated by dwpose and openpose when I was doing AI animation, the arms would be covered by the upper body at the back. Originally the arms should be displayed in front of the body, but now I can only see the body but not the arms. 
![ComfyUI_00434_](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/33535046/24a1d9b8-3421-409e-9696-986aab4c318f)
<img width="385" alt="1702641540688" src="https://github.com/Fannovel16/comfyui_controlnet_aux/assets/33535046/db559667-a1d5-4665-882f-ee7abeda1a49">

https://github.com/Fannovel16/comfyui_controlnet_aux/assets/33535046/ac81d101-af2d-4c4a-b9dc-66c747edc5a8

**Comment by Layer-norm** [comment]
It dosen't matter wheather arms behind or not. 
In fact openpose controlnet cannot distinguish such small differences. 
The openpose image you provided can also generate images with arms in front of the body with prompt `1girl`.
![arms](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/140777998/cd7a0fb3-ceb6-47d3-a636-f6cd0ba7b6ac)
You should use prompt to guide the model to generate the result you want.

**Comment by GoodGoodstudy0daydayup** [comment]
got it, maybe i should use 2 controlnet, thank you so much!
