### ISSUE TITLE
After the 2023-12-18 update, a black image will appear

### ISSUE THREAD

**Issue by Ysshis** [Fannovel16/comfyui_controlnet_aux#155]
Hello
I'm after the 2023-12-18 comfyui_controlnet_aux update

When using ControlNet
Occasional black imagery 
As long as the black image appears once, the black image will always appear after it
Comfyui needs to be restarted to get back to normal

There is no problem when ControlNet is not used

Before the 2023-12-18 update there was never a problem

Can you please fix it?
Or older versions can be offered for download

I'm using AMD+windows+DirectML

Thank you for your dedication and hard work

**Comment by Fannovel16** [comment]
Wdym? The latest commit is on 15-12-2023
