### ISSUE TITLE
Can LineArtPreprocessor only be used online?

### ISSUE THREAD

**Issue by shawpook** [Fannovel16/comfyui_controlnet_aux#157]
My cloud server is unable to connect to hugface, so one of them reported an error. However, tile and others are functioning normally. After trying to shut down the network on my personal computer, Linart still cannot be used.

got prompt
'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /lllyasviel/Annotators/resolve/main/sk_model2.pth (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 503 Service Unavailable')))' thrown while requesting HEAD https://huggingface.co/lllyasviel/Annotators/resolve/main/sk_model2.pth
WARNING:huggingface_hub.utils._http:'HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /lllyasviel/Annotators/resolve/main/sk_model2.pth (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 503 Service Unavailable')))' thrown while requesting HEAD https://huggingface.co/lllyasviel/Annotators/resolve/main/sk_model2.pth
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/urllib3/connectionpool.py", line 777, in urlopen
    self._prepare_proxy(conn)
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1046, in _prepare_proxy
    conn.connect()
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/urllib3/connection.py", line 625, in connect
    self._tunnel()  # type: ignore[attr-defined]
  File "/root/.local/conda/envs/com/lib/python3.10/http/client.py", line 925, in _tunnel
    raise OSError(f"Tunnel connection failed: {code} {message.strip()}")
OSError: Tunnel connection failed: 503 Service Unavailable

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', OSError('Tunnel connection failed: 503 Service Unavailable'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/root/.local/conda/envs/com/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /lllyasviel/Annotators/resolve/main/sk_model2.pth (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 503 Service Unavailable')))

**Comment by Layer-norm** [comment]
Download [sk_model2.pth](https://huggingface.co/lllyasviel/Annotators/resolve/main/sk_model2.pth) and [sk_model2.pth](https://huggingface.co/lllyasviel/Annotators/resolve/main/sk_model2.pth) manually and put them into `{your annotators ckpts path}/lllyasviel/Annotators/` folder. 
Restart your ComfyUI

**Comment by shawpook** [comment]
> Download [sk_model2.pth](https://huggingface.co/lllyasviel/Annotators/resolve/main/sk_model2.pth) and [sk_model2.pth](https://huggingface.co/lllyasviel/Annotators/resolve/main/sk_model2.pth) manually and put them into `{your annotators ckpts path}/lllyasviel/Annotators/` folder. Restart your ComfyUI

Thank you for your reply. I would like to know if there is a clearer location for {your annotations ckpts path}/lllyasviel/Annotators/folder. This is because of my sk_ Model2. pth and sk_ The model2.pth file is located at this location: ComfyUI \ \ custom_ Nodes \ comfyui_ Controllnet_ Aux \ ckpts \ models -- lllyasviel -- Annotators \ snapshots \ 982e7edaec38759d914a963c48c4726685de7d96 \ sk_ Model2. pth.
This is the location that I downloaded automatically when I first used it. My local PC can be connected to the internet, but when I am not using it, a new directory is not automatically created to download again

**Comment by Layer-norm** [comment]
Put them into `ComfyUI\ custom_ Nodes \ comfyui_ Controllnet_ Aux \ ckpts \lllyasviel\Annotators`
`models -- lllyasviel -- Annotators` are caches. they should be removed after dowloading.
Are you using the latest version of comfyui_controlnet_aux? 
If not, put them into  `ComfyUI\ custom_ Nodes \ comfyui_ Controllnet_ Aux \ ckpts \`

**Comment by shawpook** [comment]
> 将它们放入`ComfyUI\ custom_ Nodes \ comfyui_ Controllnet_ Aux \ ckpts \lllyasviel\Annotators` `models -- lllyasviel -- Annotators`缓存中。下载后应将其删除。 您使用的是最新版本的 comfyui_controlnet_aux 吗？ 如果没有，请将它们放入 `ComfyUI\ custom_ Nodes \ comfyui_ Controllnet_ Aux \ ckpts \`

Thank you very much, it can working
