### ISSUE TITLE
Error occurred when executing OpenposePreprocessor

### ISSUE THREAD

**Issue by yeomanzz** [Fannovel16/comfyui_controlnet_aux#166]
Error occurred when executing OpenposePreprocessor:

[Errno 2] No such file or directory: 'D:\\ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\ckpts\\lllyasviel/Annotators\\cache\\models--lllyasviel--Annotators\\blobs\\25a948c16078b0f08e236bda51a385d855ef4c153598947c28c0d47ed94bb746.incomplete'

File "D:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\openpose.py", line 27, in estimate_pose
model = OpenposeDetector.from_pretrained(HF_MODEL_NAME, cache_dir=annotator_ckpts_path).to(model_management.get_torch_device())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\open_pose\__init__.py", line 127, in from_pretrained
body_model_path = custom_hf_download(pretrained_model_or_path, filename, cache_dir=cache_dir, subfolder=subfolder)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\util.py", line 244, in custom_hf_download
model_path = hf_hub_download(repo_id=pretrained_model_or_path,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1449, in hf_hub_download
with temp_file_manager() as temp_file:
File "contextlib.py", line 137, in __enter__
File "D:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1433, in _resumable_file_manager
with open(incomplete_path, "ab") as f:
^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by maurice-ach** [comment]
Having the exact same issue

**Comment by ElGato2112** [comment]
have the same issue, I tried reinstalling but nothing any ideas?

**Comment by ElGato2112** [comment]
I solved it doing this:

- Uninstall and erase the "comfyui_controlnet_aux" folder
- Download manually the .zip file from https://github.com/Fannovel16/comfyui_controlnet_aux
- Unzip it and copying the folder in ComfyUI\custom_nodes
- Launching Comfy and installing the missing custom nodes via manager

I don't know how it works but it does! (for me at least) 
@maurice-ach @yeomanzz I hope it helps!

**Comment by maurice-ach** [comment]
Thanks for the advice @ElGato2112. I also managed to fix it in the same way that you did but didn't post 😵‍💫. Sorry for that. Can confirm it works 👍

**Comment by yeomanzz** [comment]
thanks for your advice @ElGato2112 ,but it doesn't works.

**Comment by lcicco** [comment]
Just tried @ElGato2112 solution but doesn't work. Been stuck on this for multiple hours.

My ComfyUI is trying to find '\models--lllyasviel--Annotators\\snapshots\\982e7edaec38759d914a963c48c4726685de7d96' which is slightly different from the original issue. But everything else is the same.

**Comment by Fannovel16** [comment]
@yeomanzz @lcicco Try the following steps:
1. Delete `ckpts/lllyasviel/Annotators/cache` folder
2. Manually download [body_pose_model.pth](https://huggingface.co/lllyasviel/Annotators/blob/main/body_pose_model.pth), [hand_pose_model.pth](https://huggingface.co/lllyasviel/Annotators/blob/main/hand_pose_model.pth), [facenet.pth](https://huggingface.co/lllyasviel/Annotators/blob/main/facenet.pth) and place them to `ckpts/lllyasviel/Annotators`

**Comment by yeomanzz** [comment]
> @yeomanzz @lcicco @96Asd8 Try the following steps:
> 
> 1. Delete `ckpts/lllyasviel/Annotators/cache` folder
> 2. Manually download [body_pose_model.pth](https://huggingface.co/lllyasviel/Annotators/blob/main/body_pose_model.pth), [hand_pose_model.pth](https://huggingface.co/lllyasviel/Annotators/blob/main/hand_pose_model.pth), [facenet.pth](https://huggingface.co/lllyasviel/Annotators/blob/main/facenet.pth) and place them to `ckpts/lllyasviel/Annotators`

it works！Thank you !!

**Comment by Fannovel16** [comment]
Moving to https://github.com/Fannovel16/comfyui_controlnet_aux/issues/264

**Comment by flyingrtx2333** [comment]
I also had the same issue. I first tried to manually download the .pth file and move it to the (my directory )\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\lllyasviel folder, but it didn't work for me. I think the reason is that the absolute path is too long in Windows 11, so I tried to rename the absolute directory path from D:\xxx\xxx\xxx\comfyUI to D:\ComfyUI to make it shorter. After restarting ComfyUI, it worked for me!
![H 2RGG ONQGQGG7CDK6}~YG](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/127621846/8a08d423-a685-4b43-b7c7-ffde623409ed)

**Comment by angel51026** [comment]
> > @yeomanzz @lcicco @96Asd8请尝试以下步骤：
> > 
> > 1. 删除`ckpts/lllyasviel/Annotators/cache`文件夹
> > 2. 手动下载[body_pose_model.pth](https://huggingface.co/lllyasviel/Annotators/blob/main/body_pose_model.pth)，[hand_pose_model.pth](https://huggingface.co/lllyasviel/Annotators/blob/main/hand_pose_model.pth)，[facenet.pth](https://huggingface.co/lllyasviel/Annotators/blob/main/facenet.pth)并将它们放置到`ckpts/lllyasviel/Annotators`
> 
> 它有效！谢谢！！

很有效，已解决！谢谢你！

**Comment by WAIT-TY** [comment]
> @yeomanzz @lcicco @96Asd8请尝试以下步骤：
> 
> 1. 删除`ckpts/lllyasviel/Annotators/cache`文件夹
> 2. 手动下载[body_pose_model.pth](https://huggingface.co/lllyasviel/Annotators/blob/main/body_pose_model.pth)，[hand_pose_model.pth](https://huggingface.co/lllyasviel/Annotators/blob/main/hand_pose_model.pth)，[facenet.pth](https://huggingface.co/lllyasviel/Annotators/blob/main/facenet.pth)并将它们放置到`ckpts/lllyasviel/Annotators`

感谢，对我很有效，已解决
