### ISSUE TITLE
no module controlnet.controlnet.sparsectrl and failed to load the test json file.

### ISSUE THREAD

**Issue by hanetyb** [Fannovel16/comfyui_controlnet_aux#168]
upgrade latest version, it prompt error below and reinstall twice, but same. besides, it failed to load any example PNG inside example, or test json file from website. none any response.
appreicate your advice. here.

![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/136415996/3010e865-060b-4664-8e71-a2e85588f3db)

**Comment by Fannovel16** [comment]
@hanetyb This extension doesn't have "control.control_sparsectrl" and this error is likely to come from [Efficiency Nodes](https://github.com/jags111/efficiency-nodes-comfyui/issues).
