### ISSUE TITLE
[FeatureRequest] Support for MeshGraphormer

### ISSUE THREAD

**Issue by nomadoor** [Fannovel16/comfyui_controlnet_aux#170]
A technology called [HandRefiner](https://github.com/wenquanlu/HandRefiner) that corrects hands in generated images has been released. 
Essentially, it extracts a 3D mesh of the hand from the image using [MeshGraphormer](https://github.com/microsoft/MeshGraphormer), and then does the inpainting using ControlNet. 
Since the ControlNet model is already publicly available, it should be possible to replicate this when MeshGraphormer becomes usable in ComfyUI.

**Comment by Fannovel16** [comment]
Added in https://github.com/Fannovel16/comfyui_controlnet_aux/commit/6e8d9881a03fa7de9048ddc25c10f8d75db0e02e%20https://github.com/Fannovel16/comfyui_controlnet_aux/commit/309e15e3637a108f188cc10df2ce31b8224a5ce2
