### ISSUE TITLE
Mesh Graphormer on Apple M1/2 (and DirectML)

### ISSUE THREAD

**Issue by alessandroperilli** [Fannovel16/comfyui_controlnet_aux#172]
Thank you for sharing the new Mesh Graphormer node! 

Unfortunately, the node generates a number of errors on Apple Silicon systems due, to the best of my research efforts, to the dependency of the `trimesh` package on `embreex` and `pyembree` packages.

Your requirements.txt file asks for [embreex](https://pypi.org/project/embreex/), which is not available for M1 architecture on pypi.
Without it, you can't install trimesh.

You can work around this problem by 

1. manually installing `trimesh[easy]`, by using the following syntax: `pip install 'trimesh[easy]'`
This will prevent trimesh from being upset about the missing `embreex` package.

2. manually installing `pyembree` with a standard `pip install pyembree`, but the latter won't install anything newer than version 0.1.12 (latest is 0.2.11).

Yet, after all this effort (which took me a while to figure out), the node still generates the following error:

>   File "/ComfyUI/execution.py", line 154, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ComfyUI/execution.py", line 84, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ComfyUI/execution.py", line 77, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/mesh_graphormer.py", line 54, in execute
>     from controlnet_aux.mesh_graphormer import MeshGraphormerDetector
>   File "/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/mesh_graphormer/__init__.py", line 5, in <module>
>     from controlnet_aux.mesh_graphormer.pipeline import MeshGraphormerMediapipe, args
>   File "/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/mesh_graphormer/pipeline.py", line 33, in <module>
>     from trimesh.ray.ray_pyembree import RayMeshIntersector
>   File "/ComfyUI/venv/lib/python3.11/site-packages/trimesh/ray/ray_pyembree.py", line 10, in <module>
>     from pyembree import rtcore_scene
> ImportError: cannot import name 'rtcore_scene' from 'pyembree' (/ComfyUI/venv/lib/python3.11/site-packages/pyembree/__init__.py)

I don't know if there's a way out of this, so this PR is primarily to inform Mac users of the issue. But if there's a way out, I'd appreciate your guidance.

Thank you!

**Comment by Fannovel16** [comment]
I found out a simple way to fix it: Just replace `trimesh.ray.ray_embree` with `trimesh.ray.ray_triangle`. It's a bit slower tho

**Comment by alessandroperilli** [comment]
That's great! 
Can you be a bit more specific about the replacement operation? 

I assume I'd still install `trimesh[easy]` rather than the `trimesh` standard package. Then, where would I change the string as you indicated?

Are you suggesting that I rename `ray_triangle` as `ray_embree` in `/ComfyUI/venv/lib/python3.xy/site-packages/trimesh/ray` or that I change the call in one of the custom node suite files?

Thank you for finding a solution so quickly.

**Comment by alessandroperilli** [comment]
I have seen the changes in the last commit. Thank you! 

Upon running the node, now, I have this error:

> File "/ComfyUI/execution.py", line 154, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ComfyUI/execution.py", line 84, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ComfyUI/execution.py", line 77, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/mesh_graphormer.py", line 57, in execute
>     model = MeshGraphormerDetector.from_pretrained("hr16/ControlNet-HandRefiner-pruned", cache_dir=annotator_ckpts_path).to(model_management.get_torch_device())
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/mesh_graphormer/__init__.py", line 17, in from_pretrained
>     pipeline = MeshGraphormerMediapipe(args)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/mesh_graphormer/pipeline.py", line 131, in __init__
>     model = model_class(config=config)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_mesh_graphormer/modeling/bert/modeling_graphormer.py", line 303, in __init__
>     self.bert = EncoderBlock(config)
>                 ^^^^^^^^^^^^^^^^^^^^
>   File "/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_mesh_graphormer/modeling/bert/modeling_graphormer.py", line 209, in __init__
>     self.encoder = GraphormerEncoder(config)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_mesh_graphormer/modeling/bert/modeling_graphormer.py", line 173, in __init__
>     self.layer = nn.ModuleList([GraphormerLayer(config) for _ in range(config.num_hidden_layers)])
>                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_mesh_graphormer/modeling/bert/modeling_graphormer.py", line 173, in <listcomp>
>     self.layer = nn.ModuleList([GraphormerLayer(config) for _ in range(config.num_hidden_layers)])
>                                 ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_mesh_graphormer/modeling/bert/modeling_graphormer.py", line 131, in __init__
>     self.graph_conv = GraphResBlock(config.hidden_size, config.hidden_size, mesh_type=self.mesh_type)
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_mesh_graphormer/modeling/_gcnn.py", line 70, in __init__
>     self.conv = GraphConvolution(out_channels // 2, out_channels // 2, mesh_type)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/custom_mesh_graphormer/modeling/_gcnn.py", line 146, in __init__
>     self.adjmat = torch.sparse_coo_tensor(adj_indices, adj_mat_value, size=adj_mat_size).to(device)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> NotImplementedError: Could not run 'aten::empty.memory_format' with arguments from the 'SparseMPS' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::empty.memory_format' is only available for these backends: [CPU, MPS, Meta, QuantizedCPU, QuantizedMeta, MkldnnCPU, SparseCPU, SparseMeta, SparseCsrCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradMeta, AutogradNestedTensor, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, BatchedNestedTensor, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].
> 
> CPU: registered at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/RegisterCPU.cpp:31357 [kernel]
> MPS: registered at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/RegisterMPS.cpp:27257 [kernel]
> Meta: registered at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/RegisterMeta.cpp:26984 [kernel]
> QuantizedCPU: registered at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/RegisterQuantizedCPU.cpp:944 [kernel]
> QuantizedMeta: registered at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/RegisterQuantizedMeta.cpp:105 [kernel]
> MkldnnCPU: registered at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/RegisterMkldnnCPU.cpp:515 [kernel]
> SparseCPU: registered at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/RegisterSparseCPU.cpp:1387 [kernel]
> SparseMeta: registered at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/RegisterSparseMeta.cpp:249 [kernel]
> SparseCsrCPU: registered at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/RegisterSparseCsrCPU.cpp:1135 [kernel]
> BackendSelect: registered at /Users/runner/work/pytorch/pytorch/pytorch/build/aten/src/ATen/RegisterBackendSelect.cpp:807 [kernel]
> Python: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:154 [backend fallback]
> FuncTorchDynamicLayerBackMode: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/functorch/DynamicLayer.cpp:498 [backend fallback]
> Functionalize: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/FunctionalizeFallbackKernel.cpp:324 [backend fallback]
> Named: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
> Conjugate: fallthrough registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/ConjugateFallback.cpp:21 [kernel]
> Negative: fallthrough registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/NegateFallback.cpp:23 [kernel]
> ZeroTensor: fallthrough registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/ZeroTensorFallback.cpp:90 [kernel]
> ADInplaceOrView: fallthrough registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/core/VariableFallbackKernel.cpp:86 [backend fallback]
> AutogradOther: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:19038 [autograd kernel]
> AutogradCPU: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:19038 [autograd kernel]
> AutogradCUDA: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:19038 [autograd kernel]
> AutogradHIP: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:19038 [autograd kernel]
> AutogradXLA: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:19038 [autograd kernel]
> AutogradMPS: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:19038 [autograd kernel]
> AutogradIPU: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:19038 [autograd kernel]
> AutogradXPU: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:19038 [autograd kernel]
> AutogradHPU: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:19038 [autograd kernel]
> AutogradVE: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:19038 [autograd kernel]
> AutogradLazy: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:19038 [autograd kernel]
> AutogradMTIA: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:19038 [autograd kernel]
> AutogradPrivateUse1: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:19038 [autograd kernel]
> AutogradPrivateUse2: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:19038 [autograd kernel]
> AutogradPrivateUse3: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:19038 [autograd kernel]
> AutogradMeta: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:19038 [autograd kernel]
> AutogradNestedTensor: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/VariableType_2.cpp:19038 [autograd kernel]
> Tracer: registered at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/generated/TraceType_2.cpp:17346 [kernel]
> AutocastCPU: fallthrough registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/autocast_mode.cpp:378 [backend fallback]
> AutocastCUDA: fallthrough registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/autocast_mode.cpp:244 [backend fallback]
> FuncTorchBatched: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/functorch/LegacyBatchingRegistrations.cpp:720 [backend fallback]
> BatchedNestedTensor: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/functorch/LegacyBatchingRegistrations.cpp:746 [backend fallback]
> FuncTorchVmapMode: fallthrough registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/functorch/VmapModeRegistrations.cpp:28 [backend fallback]
> Batched: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/LegacyBatchingRegistrations.cpp:1075 [backend fallback]
> VmapMode: fallthrough registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
> FuncTorchGradWrapper: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/functorch/TensorWrapper.cpp:203 [backend fallback]
> PythonTLSSnapshot: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:162 [backend fallback]
> FuncTorchDynamicLayerFrontMode: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/functorch/DynamicLayer.cpp:494 [backend fallback]
> PreDispatch: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:166 [backend fallback]
> PythonDispatcher: registered at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/core/PythonFallbackKernel.cpp:158 [backend fallback]

**Comment by Fannovel16** [comment]
@alessandroperilli Related issue: https://github.com/pytorch/pytorch/issues/87886

**Comment by Fannovel16** [comment]
@alessandroperilli I don't have a MacBook. Can you try the following method?
1. Search for "sparse_coo_tensor" in the codebase
2. Add `.to_dense()` or `.to_dense().to(device)`

**Comment by alessandroperilli** [comment]
It works perfectly, thank you. 

The files to edit are:

- _gcnn.py
- _mano.py
- _smpl.py

I attached the modified versions, just in case anybody wants to see the edit I made:

[Dense.zip](https://github.com/Fannovel16/comfyui_controlnet_aux/files/13805025/Dense.zip)

The node performs quite fast on my machine and this is the result:

<img width="1155" alt="Screenshot 2024-01-01 at 15 11 24" src="https://github.com/Fannovel16/comfyui_controlnet_aux/assets/9775949/54bf0bbe-1289-4817-8d1b-7690e6c2079c">

**Comment by Fannovel16** [comment]
I added a function which will automatically convert sparse tensors to dense tensors on MPS and DirectML device
