### ISSUE TITLE
Preprocessor resolution is always 512x512

### ISSUE THREAD

**Issue by AlexPlaycorp** [Fannovel16/comfyui_controlnet_aux#18]
Hello,
It seems that regardless of the input image resolution, the lineart preprocessor is always 512x512, then the image is upscaled to whatever the input resolution is set to, after it's been processed. You can see be saving out the processed image and seeing the upscaled pixels.

I have tested this by changing the default resolution properties in class **LineartDetector** line 126.
`    def __call__(self, input_image, coarse=False, detect_resolution=512, image_resolution=512, output_type="pil", **kwargs):`

Setting the default 512 resolutions here to higher values such as 1024 will process at 1024 instead of 512. I guess the resolutions are never set so they are always default.

Thanks for your time and making such great tools!

**Comment by AlexPlaycorp** [comment]
I just hack fixed it locally by setting both the `detect_resolution` and `image_resolution` to the same value at the top of each preprocessor function.

```
        image_resolution = max(input_image.shape[0], input_image.shape[1])
        detect_resolution = image_resolution
```

**Comment by Fannovel16** [comment]
Fixed at https://github.com/Fannovel16/comfyui_controlnet_aux/commit/79bfbd7b26fd335246d478501aebc7c4d119036b and previous `i` commits.
