### ISSUE TITLE
can't use Mesh HandRefiner on ComfyUI

### ISSUE THREAD

**Issue by PrideOfHiigara** [Fannovel16/comfyui_controlnet_aux#180]
I have used ComfyUI-Manager to install comfy_controlnet_aux to my ComfyUI and restart it, but i can't find MeshGraphormer Hand Refiner node in my ComfyUI. Did i miss some steps? if I need install HandRefiner and MeshGraphormer  separately, which fold should I install? Thx!

**Comment by PrideOfHiigara** [comment]
ps: no error report when I start ComfyUI, and I run ComfyUI on Linux

**Comment by PrideOfHiigara** [comment]
my python version is 3.10, does this matter?

**Comment by Fannovel16** [comment]
> I have used ComfyUI-Manager to install comfy_controlnet_aux to my ComfyUI and restart it, but i can't find MeshGraphormer Hand Refiner node in my ComfyUI
Try to remove comfy_controlnet_aux then re-install

> if I need install HandRefiner and MeshGraphormer separately, which fold should I install? Thx!
HandRefiner pipeline consists of two things: hand-correction preprocessor MeshGraphormer and [inpaint_depth_hand ControlNet](https://huggingface.co/hr16/ControlNet-HandRefiner-pruned/blob/main/control_sd15_inpaint_depth_hand_fp16.safetensors)

**Comment by PrideOfHiigara** [comment]
@Fannovel16 Thx for your reply and it works well
