### ISSUE TITLE
Preprocessor Resolution Doesn't Match input image

### ISSUE THREAD

**Issue by ckao10301** [Fannovel16/comfyui_controlnet_aux#184]
How does the "resolution" setting in the preprocessor node work? Does the value apply to the width, height, or longest side, etc? More documentation would be helpful. My input image was 683x1024, and my images are always 1024 on the longest side with different aspect ratios. I set "resolution" in the node as 1024. But the preprocessor image output is
 1024x1535, which doesn't match the input of 683x1024.

Can we add option to use the longest side as the setting for the resolution?
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/129625358/abf2437f-6643-4317-88f6-8474a8fa41f7)

**Comment by Layer-norm** [comment]
This resolution refers to the receptive field not image, and output image resolution should always match imput image. However, I recommend that your image size be a multiple of 64.

**Comment by ckao10301** [comment]
Hi what do you mean by receptive field?

**Comment by ckao10301** [comment]
From my testing it seems to be referring to the shortest length of the
preprocessor output image

**Comment by ckao10301** [comment]
From my testing it seems to be referring to the shortest length of the
preprocessor output image
Example:

Input Image: 4553x6829
Depth Map Image: 1024x1536


<img width="806" alt="Screenshot 2024-01-04 175113" src="https://github.com/Fannovel16/comfyui_controlnet_aux/assets/129625358/429a5281-203f-4d1c-8d73-25a4515e2a36">

**Comment by Layer-norm** [comment]
Yes you are right, I confused this with other project. 
It will resize with shorter side.  
`min(height, width)` = 1024
1024 * (4553/6829) = 1536

**Comment by stephantual** [comment]
I had the same issue - you can easily fix it by resizing the source to an sdxl compatible one (multiple nodes for this), then use comfy logic nodes to check width against height, and flip the outputs if a>b - works a charm.

**Comment by ckao10301** [comment]
> I had the same issue - you can easily fix it by resizing the source to an sdxl compatible one (multiple nodes for this), then use comfy logic nodes to check width against height, and flip the outputs if a>b - works a charm.

Yes that is a great idea. Thanks all.

**Comment by ckao10301** [comment]
> Yes you are right, I confused this with other project. It will resize with shorter side. `min(height, width)` = 1024 1024 * (4553/6829) = 1536

Thanks for confirming, it'd be helpful to update the documentation with this.
