### ISSUE TITLE
Animal Pose Estimation (AP10K) crashes if no animal is found. "cannot unpack non-iterable NoneType object"

### ISSUE THREAD

**Issue by tt19803272** [Fannovel16/comfyui_controlnet_aux#186]
Can reproduce by plugging an empty image into the pose estimator.

I was able to get around this by returning a blank `detected_map` if `self.animal_pose_estimation(input_image)` was of type `None`

Are there other solutions that might fix this problem?

**Comment by Fannovel16** [comment]
That case should be addressed now, Remember to `git stash` before update

**Comment by stephantual** [comment]
Can confirm it appears fixed - no animal detected = black output which is expected. 👍
