### ISSUE TITLE
comfyui_controlnet_aux error when reactor or roop with it 

### ISSUE THREAD

**Issue by shiyk92** [Fannovel16/comfyui_controlnet_aux#19]
[comfyui_controlnet_aux] | STATUS -> Some nodes failed to load:
        Failed to import module bae because TypeError: A Message class can only inherit from Message
        Failed to import module hed because TypeError: A Message class can only inherit from Message
        Failed to import module leres because TypeError: A Message class can only inherit from Message
        Failed to import module lineart because TypeError: A Message class can only inherit from Message
        Failed to import module lineart_anime because TypeError: A Message class can only inherit from Message
        Failed to import module manga_line because TypeError: A Message class can only inherit from Message
        Failed to import module midas because TypeError: A Message class can only inherit from Message
        Failed to import module mlsd because TypeError: A Message class can only inherit from Message
        Failed to import module openpose because TypeError: A Message class can only inherit from Message
        Failed to import module pidinet because TypeError: A Message class can only inherit from Message
        Failed to import module scribble because TypeError: A Message class can only inherit from Message
        Failed to import module simple_cv2 because TypeError: A Message class can only inherit from Message
        Failed to import module zoe because TypeError: A Message class can only inherit from Message

Check that you properly installed the dependencies.
If you think this is a bug, please report it on the github page (https://github.com/Fannovel16/comfyui_controlnet_aux/issues)

**Comment by Fannovel16** [comment]
@shiyk92 Try the fix in https://github.com/Fannovel16/comfyui_controlnet_aux/issues/7#issuecomment-1699499731

If you still have that issue, please comment on that page.

**Comment by Fannovel16** [comment]
Closed as this is duplication of https://github.com/Fannovel16/comfyui_controlnet_aux/issues/7
