### ISSUE TITLE
Examples seem to be missing workflow metadata

### ISSUE THREAD

**Issue by michaelriedl** [Fannovel16/comfyui_controlnet_aux#194]
The example .png files do not load any workflow data into ComfyUI.

**Comment by jkrauss82** [comment]
+1, tried the meshgraphormer example, nothing in there seemingly

**Comment by ghostsquad** [comment]
The images in `examples` aren't really examples. Maybe they could be moved to `doc/assets` instead, because that's all they are, images used in the `README.md`. Similarly, I came here to get some more information on how to use the mesh graphormer nodes.
