### ISSUE TITLE
Face part segmentation

### ISSUE THREAD

**Issue by txs** [Fannovel16/comfyui_controlnet_aux#195]
I'm currently working on face part segmentation.
I saw you allow the keypoints to be downloaded which is pretty awesome!
Is it possible to add specific facical part for dwpose and openpose so that we can generate point mask out of it?
For example, left_eye true, left_eyebrow false, left_pupil true

Or different color map for different facial part like mediapipe face mesh, so that we can use imagecolortomap for post proccessing
![surprised_annotation](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/554329/692a289d-bb20-42c3-bdf4-bf9092579a30)

**Comment by Fannovel16** [comment]
@txs 
> Is it possible to add specific facical part for dwpose and openpose so that we can generate point mask out of it?

DWPose is a 2D Pose Estimator which produces 2D landmarks on human body.
![](https://github.com/jin-s13/COCO-WholeBody/raw/master/imgs/Fig2_anno.png)

The format of JSON file
```
[{
    "people": [
        {
            'pose_keypoints_2d': [[x1, y1, 1], [x2, y2, 1],..., [x17, y17, 1]]
            "face_keypoints_2d": [[x1, y1, 1], [x2, y2, 1],..., [x68, y68, 1]],
            "hand_left_keypoints_2d": [[x1, y1, 1], [x2, y2, 1],..., [x21, y21, 1]],
            "hand_right_keypoints_2d":[[x1, y1, 1], [x2, y2, 1],..., [x21, y21, 1]],
        }
    ],
    "canvas_height": canvas_height,
    "canvas_width": canvas_width,
},...]
```

**Comment by txs** [comment]
> facial landmark detection

I'm using it on anime characters and openpose is a little bit better than dwpose. Mediapipe is completely broken for my characters.

**Comment by txs** [comment]
I would like it to be drawn in volumetric like 2020 Lapa
<img width="408" alt="Screenshot_2021-01-29_at_13 43 07" src="https://github.com/Fannovel16/comfyui_controlnet_aux/assets/554329/a3b12501-0817-4d56-a413-d42c0178df0f">

**Comment by txs** [comment]
Turn the keypoints to polygon and drawn out like the following format.
[{
    "people": [
        {
            'pose_keypoints_2d': [[x1, y1, 1], [x2, y2, 1],..., [x17, y17, 1]],
            "face_keypoints_2d": [[x1, y1, 1], [x2, y2, 1],..., [x68, y68, 1]],
            "hand_left_keypoints_2d": [[x1, y1, 1], [x2, y2, 1],..., [x21, y21, 1]],
            "hand_right_keypoints_2d":[[x1, y1, 1], [x2, y2, 1],..., [x21, y21, 1]]
        }
    ],
    "face":[
        {
            'left_eyebrow': [[x41, y41, 1], [x42, y42, 1],..., [x45, y45, 1],...,[x42, y42, 1], [x41, y41, 1]],
            "left_eye": [[x60, y60, 1], [x61, y61, 1],..., [x65, y65, 1], [x60, y60, 1]],
            "left_iris": [[x61, y61, 1], [x62, y62, 1], [x64, y64, 1], [x65, y65, 1], [x61, y61, 1]]
        }
    ],
    "face_color":[
        {
            'left_eyebrow': 6750105,
            "left_eye": 16711527,
            "left_iris": 7798631
        }
    ],
    "canvas_height": canvas_height,
    "canvas_width": canvas_width,
},...]

**Comment by Fannovel16** [comment]
@txs Hmm I think a masking node which create masks over body/face parts would be a better approach

**Comment by Fannovel16** [comment]
Just re-thinking, the masks of multiple parts will overlap on each other 😅
