### ISSUE TITLE
MiDaS depth performance on A100

### ISSUE THREAD

**Issue by ynie** [Fannovel16/comfyui_controlnet_aux#196]
Hello, I'm running the MiDaS node on A100, but it takes 5s to finish for an 1024 input image. I have all the default settings  in the node:

<img width="213" alt="image" src="https://github.com/Fannovel16/comfyui_controlnet_aux/assets/394026/a5bf7204-9d78-482e-9934-d66888b5aca4">

For comparison, it only takes 2.5s on my M3 MBP. is there any settings I need to enable to fix the performance issue on A100? Thanks!

**Comment by Fannovel16** [comment]
@ynie Do you use MiDaS to process images in batch or just single image? To make preprocessor nodes plug-and-play, I don't make a model loader node, which means every time they re-run, the model required will be loaded and deleted, making noticeable warmup time.

**Comment by ynie** [comment]
Thank you! It’s just one image. I’m still new to the comfyAPI, could you give me some hint on how to change the code to keep the model in memory as long as possible? I’m also curious, why not use the comfyUI memory management to unload the model when there’s a memory pressure? Thanks!

**Comment by Fannovel16** [comment]
@ynie 
> could you give me some hint on how to change the code to keep the model in memory as long as possible?

You can import custom nodes like a normal Python module:
```py
import sys
from pathlib import Path

COMFYUI_PATH = "E:\\ComfyUI"
EXT_PATH = "E:\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux"

#Register ComfyUI to sys.path for module import
sys.path.insert(0, str(Path(COMFYUI_PATH).resolve()))
sys.path.insert(0, str(Path(COMFYUI_PATH, "comfy").resolve()))

#Register extension to sys.path for module import
sys.path.insert(0, str(Path(EXT_PATH, "src").resolve()))
for pkg_name in ["controlnet_aux", "custom_mmpkg"]:
    sys.path.append(str(Path(here, "src", pkg_name).resolve()))

import comfy.model_management as model_management
from controlnet_aux.midas import MidasDetector
model = MidasDetector.from_pretrained().to(model_management.get_torch_device())
np_image = model(hwc_input_image, resolution)
```

**Comment by ynie** [comment]
@Fannovel16 Thank you so much. Just want to make sure I fully understan: if the workflow didn’t change and only the input image is changing, the Midas control net node still load and unload the model for each processing. The ComfyUI memory managements only applies to loading the SD checkpoints, not custom nodes. Correct?

**Comment by Fannovel16** [comment]
@ynie 
> if the workflow didn’t change and only the input image is changing, the Midas control net node still load and unload the model for each processing.

That's right

> The ComfyUI memory managements only applies to loading the SD checkpoints, not custom nodes. 

Yep. In the case of custom nodes, the caching is applied to the output of node. A model loader node (for anything besides SD, LoRA) will cache the model in RAM until it's deleted. This extension has like 10 neural-network-based for preprocessor, which mean if I want the model to be cached, I will have to make 10 nodes. That is inconvenient for both devs and end-users

**Comment by ynie** [comment]
Got it. Thank you for the amazing work.

**Comment by WooXinyi** [comment]
Now I have encountered a similar issue. When using the MiDaS node in the editor, the model is not reloaded with each repeated run. However, when using the API call, the model reloads every time. Could you explain why this happens?

**Comment by WooXinyi** [comment]
> @ynie
> 
> > could you give me some hint on how to change the code to keep the model in memory as long as possible?
> 
> You can import a fork of controlnet_aux inside of this extension:
> 
> ```python
> import sys
> from pathlib import Path
> from PIL import Image
> 
> COMFYUI_PATH = "E:\\ComfyUI"
> EXT_PATH = "E:\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux"
> 
> #Register ComfyUI to sys.path for module import
> sys.path.insert(0, str(Path(COMFYUI_PATH).resolve()))
> sys.path.insert(0, str(Path(COMFYUI_PATH, "comfy").resolve()))
> 
> #Register extension to sys.path for module import
> sys.path.insert(0, str(Path(EXT_PATH, "src").resolve()))
> for pkg_name in ["controlnet_aux", "custom_mmpkg"]:
>     sys.path.append(str(Path(here, "src", pkg_name).resolve()))
> 
> import comfy.model_management as model_management
> from controlnet_aux.midas import MidasDetector
> model = MidasDetector.from_pretrained().to(model_management.get_torch_device())
> hwc_input_image = np.array(Image.open("example.png").convert("RGB"))
> np_image = model(hwc_input_image, resolution=1024)
> ```

Hello，Where is this code used?
