### ISSUE TITLE
No module named 'timm'

### ISSUE THREAD

**Issue by stevehooker** [Fannovel16/comfyui_controlnet_aux#20]
I'm running my ComfyUI on Google CoLab.  I'm trying to run through the comfyui_controlnet_aux test_cn_aux_full.json This is the test with all the variations. I'm getting four errors all named 'timm'
Error occurred when executing SAMPreprocessor:
No module named 'timm'
https://pastebin.com/UHd3Dq6Z

Error occurred when executing Zoe-DepthMapPreprocessor:
No module named 'timm'
https://pastebin.com/KqM5bK6u

Error occurred when executing MiDaS-NormalMapPreprocessor:
No module named 'timm'
https://pastebin.com/V6aWDtth

Error occurred when executing MiDaS-DepthMapPreprocessor:
No module named 'timm'
https://pastebin.com/8Nnf4NX6

Also, I'm getting two errors named 'fvcore'
Error occurred when executing OneFormer-COCO-SemSegPreprocessor:
No module named 'fvcore'
https://pastebin.com/iLpnCP8G

Error occurred when executing OneFormer-ADE20K-SemSegPreprocessor:
No module named 'fvcore'
https://pastebin.com/teJcyQJT

And one 
Error occurred when executing FakeScribblePreprocessor:
name 'HEDdetector' is not defined
https://pastebin.com/JnFP0LxF

Hope this helps.

**Comment by LukeOvermind** [comment]
Also Google Colab user here. I also got "timm issue". Reinstalling [ComfyUI's ControlNet Auxiliary Preprocessors] and then restarting the colab runtime everything works fine. However when deleting the runtime and starting the colab up agian give the "timm" error message again. Running !pip install timm leads to the following error

Error occurred when executing Zoe-DepthMapPreprocessor:

Error(s) in loading state_dict for ZoeDepth:
Unexpected key(s) in state_dict: "core.core.pretrained.model.blocks.0.attn.relative_position_index", "core.core.pretrained.model.blocks.1.attn.relative_position_index", "core.core.pretrained.model.blocks.2.attn.relative_position_index", "core.core.pretrained.model.blocks.3.attn.relative_position_index", "core.core.pretrained.model.blocks.4.attn.relative_position_index", "core.core.pretrained.model.blocks.5.attn.relative_position_index", "core.core.pretrained.model.blocks.6.attn.relative_position_index", "core.core.pretrained.model.blocks.7.attn.relative_position_index", "core.core.pretrained.model.blocks.8.attn.relative_position_index", "core.core.pretrained.model.blocks.9.attn.relative_position_index", "core.core.pretrained.model.blocks.10.attn.relative_position_index", "core.core.pretrained.model.blocks.11.attn.relative_position_index", "core.core.pretrained.model.blocks.12.attn.relative_position_index", "core.core.pretrained.model.blocks.13.attn.relative_position_index", "core.core.pretrained.model.blocks.14.attn.relative_position_index", "core.core.pretrained.model.blocks.15.attn.relative_position_index", "core.core.pretrained.model.blocks.16.attn.relative_position_index", "core.core.pretrained.model.blocks.17.attn.relative_position_index", "core.core.pretrained.model.blocks.18.attn.relative_position_index", "core.core.pretrained.model.blocks.19.attn.relative_position_index", "core.core.pretrained.model.blocks.20.attn.relative_position_index", "core.core.pretrained.model.blocks.21.attn.relative_position_index", "core.core.pretrained.model.blocks.22.attn.relative_position_index", "core.core.pretrained.model.blocks.23.attn.relative_position_index".

File "/content/drive/MyDrive/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/content/drive/MyDrive/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/content/drive/MyDrive/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/content/drive/MyDrive/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/zoe.py", line 18, in execute
model = ZoeDetector.from_pretrained(HF_MODEL_NAME, cache_dir=annotator_ckpts_path).to(model_management.get_torch_device())
File "/content/drive/MyDrive/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/zoe/__init__.py", line 30, in from_pretrained
model.load_state_dict(torch.load(model_path, map_location=torch.device('cpu'))['model'])
File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

**Comment by LukeOvermind** [comment]
I am sorry but is there any solution I can try to fix this?

**Comment by aegis72** [comment]
I'm getting this tonight based off of a just downloaded version of Comfy Windows Portable. My workflow previously worked, but getting this same issue now.

**Comment by Fannovel16** [comment]
Fixed in https://github.com/Fannovel16/comfyui_controlnet_aux/commit/6ee6d0998926832141063f0c947bc2c1495eda7c. Reinstall/update the extension should fix it
