### ISSUE TITLE
Shuffle update per que? Same as Auto 1111

### ISSUE THREAD

**Issue by moon47usaco** [Fannovel16/comfyui_controlnet_aux#202]
The shuffle preprocessor should be able to update the image shuffle every time the generation que is pressed.

At least that is how it was used in Auto 1111.

Every generation would give a new shuffled output to the sampler from the input image.

I used to use it for slight variations without changing the seed or other inputs.

In ComfyUI with the current shuffle preprocessor it generates one shuffled image per session. I have to restart comfy to get a new shuffle. 

Changing the resolution will also force a re-generation of the shuffle.

**Comment by Fannovel16** [comment]
Image shuffle now update the result every time "Queue Prompt" is clicked. `seed` and `control_after_generate` are similar to ones in KSampler node
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/16047777/0c939612-e14e-4eb5-b947-284dd621e489)

**Comment by moon47usaco** [comment]
That was fast... =]

Thank you so much.
