### ISSUE TITLE
MediaPipe Face Mesh low chance of detecting faces

### ISSUE THREAD

**Issue by lingondricka2** [Fannovel16/comfyui_controlnet_aux#204]
Most often it either won't detect the face or think another part of the body is the face.

I've tried masking the faces and upscaling x4, It didn't help.

**Comment by Fannovel16** [comment]
@lingondricka2 Is your input image realisitic?

**Comment by Fannovel16** [comment]
@lingondricka2 Can you post some example images?

**Comment by lingondricka2** [comment]
![screen1](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/155384738/043f7dc5-53af-4835-be48-dbdc2e758d0f)
![ComfyUI_01128_](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/155384738/9015c117-cc6c-4853-87e4-f167672145a3)
![bg day18 (31)](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/155384738/7a415d53-5312-47ba-8ce1-34b8a6d618ec)

**Comment by Fannovel16** [comment]
@lingondricka2 Mediapipe is only trained on camera images so anime and 3D won't work
