### ISSUE TITLE
About HANDS... PRE ANNOTATOR / GUIDED REFINER ?

### ISSUE THREAD

**Issue by RGX650** [Fannovel16/comfyui_controlnet_aux#205]
In a real life scenario, 
controlling and customizing handpose is quite challenging besides being able to generate it consistently.

I mean, lets redefine the very first starting points: it can be only by 2 possibilities: 
- reference image
- pose data

input quality, interpretability, consitency BUT ALSO ability to be really controlled, finetuned or adjusted in time!

PRE ANNOTATOR / GUIDED REFINER ?

PRE ANNOTATOR:
I am wondering, would it be relevant, possible to consider a "pre-annotator" that would snapshot a UltraLeap Leapmotion controller pose.
That "pre-annotator" would then be used to guide/finetune any exising pose related annotators & controlnets: 
(handrefiner, openpose hand, dwpose, densepose, "sided mediapipe R/L hand(futur?)

GUIDED REFINER: 
Offical pytorch implementation of "HandOccNet: Occlusion-Robust 3D Hand Mesh Estimation Network", CVPR 2022.
https://github.com/namepllet/HandOccNet.git

**Comment by Fannovel16** [comment]
@RGX650 
> PRE ANNOTATOR:
I am wondering, would it be relevant, possible to consider a "pre-annotator" that would snapshot a UltraLeap Leapmotion controller pose.
That "pre-annotator" would then be used to guide/finetune any exising pose related annotators & controlnets:
(handrefiner, openpose hand, dwpose, densepose, "sided mediapipe R/L hand(futur?)

I don't think "finetune" is the proper terminology. Anyway, that's possible but not in the domain of this extension. You can ditch the annotators and just convert whatever it outputs to 2D keypoints (openpose) or 3D mesh through some math

> GUIDED REFINER:
Offical pytorch implementation of "HandOccNet: Occlusion-Robust 3D Hand Mesh Estimation Network", CVPR 2022.
https://github.com/namepllet/HandOccNet.git

I think MeshGraphormer which is used in HandRefiner is accurate enough. What matters the result most is not these hand reconstruction models but the ControlNet and SD themselves
