### ISSUE TITLE
(IMPORT FAILED) ComfyUI's ControlNet Auxiliary Preprocessors

### ISSUE THREAD

**Issue by jeantnd** [Fannovel16/comfyui_controlnet_aux#208]
Hi folks, I tried download the [ComfyUI's ControlNet Auxiliary Preprocessors](https://github.com/Fannovel16/comfyui_controlnet_aux) in the ComfyUI Manager. I ended up with "Import Failed" and I couldn't know how to fix.

terminal return:
Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux module for custom nodes: module 'cv2.gapi.wip.draw' has no attribute 'Text'

![Screenshot 2024-01-15 144927](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/96947310/f8d280e8-c6fe-4039-b36a-fe1abaf9d501)

**Comment by jeantnd** [comment]
found the solution. i has something to do with reactor & controlnet preprocessor installations

link below
[https://github.com/Gourieff/comfyui-reactor-node/issues/45#issuecomment-1734300985](url)

**Comment by Burzennnn** [comment]
Did you figure it out? I have this problem and the link you have provided does not work anymore. Do you have a solution?:)

**Comment by jeantnd** [comment]
does this link work?
https://github.com/Gourieff/comfyui-reactor-node/issues/112

**Comment by Burzennnn** [comment]
Yes it works! Thank you ill get on that.

**Comment by solosox** [comment]
> does this link work?
> [Gourieff/comfyui-reactor-node#112](https://github.com/Gourieff/comfyui-reactor-node/issues/112)
> […](#)

This does not work anymore :_(

**Comment by esokullu** [comment]
yes what's the solution???
