### ISSUE TITLE
May I ask if this project can be joined?

### ISSUE THREAD

**Issue by 253701** [Fannovel16/comfyui_controlnet_aux#217]
https://github.com/LiheYoung/Depth-Anything

Will it be useful to us

**Comment by Fannovel16** [comment]
I just added it to my repo. The code is so clean and simple so it's pretty easy
https://github.com/Fannovel16/comfyui_controlnet_aux/commit/8da67c56a3f01ad190982dfc7386f6e7e8e5c0d6
