### ISSUE TITLE
Depth Anything Models Released 

### ISSUE THREAD

**Issue by BuffMcBigHuge** [Fannovel16/comfyui_controlnet_aux#219]
https://huggingface.co/spaces/LiheYoung/Depth-Anything/tree/main/checkpoints

https://github.com/LiheYoung/Depth-Anything

FYI

**Comment by WARRIORPSIX** [comment]
it would be cool if this was added

**Comment by Fannovel16** [comment]
@BuffMcBigHuge @WARRIORPSIX I already added them after like, serveral hours after it had released
https://github.com/Fannovel16/comfyui_controlnet_aux?tab=readme-ov-file#depth-anything--zoe-depth-anything

**Comment by tristan22mc** [comment]
These models no longer automatically download
