### ISSUE TITLE
comfyui portable version to install latest git repo, got dependency error

### ISSUE THREAD

**Issue by leeleilei** [Fannovel16/comfyui_controlnet_aux#22]
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

**Comment by Fannovel16** [comment]
That is just a warning, not an error from my side so I can't fix it.
