### ISSUE TITLE
Error occurred when executing DWPreprocessor: Unknown C++ exception from OpenCV code | comfyui portable version 

### ISSUE THREAD

**Issue by hightechpresha** [Fannovel16/comfyui_controlnet_aux#23]
When I run the workflow from the following file I get the following error:

This error appears in the console:

got prompt
C:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\__init__.py:175: UserWarning: Currently DWPose doesn't support CUDA out-of-the-box.
  warnings.warn("Currently DWPose doesn't support CUDA out-of-the-box.")

Error occurred when executing DWPreprocessor:
Unknown C++ exception from OpenCV code

File "C:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 28, in estimate_pose
out = common_annotator_call(model, image, include_hand=detect_hand, include_face=detect_face, include_body=detect_body)
File "C:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 28, in common_annotator_call
np_result = model(np_image, output_type="np", **kwargs)
File "C:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\__init__.py", line 204, in __call__
poses = self.detect_poses(input_image)
File "C:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\__init__.py", line 180, in detect_poses
keypoints_info = self.dw_pose_estimation(oriImg.copy())
File "C:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\wholebody.py", line 29, in __call__
det_result = inference_detector(self.session_det, oriImg)
File "C:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\cv_ox_det.py", line 103, in inference_detector
output = session.forward(outNames)

[example.zip](https://github.com/Fannovel16/comfyui_controlnet_aux/files/12449002/example.zip)

**Comment by selfitisolated** [comment]
some problem, do anyone fix this?

**Comment by redparisAI** [comment]
Same problem...what version of Cuda should I use? Is the requirements.txt up to date?

**Comment by ivoyavoya** [comment]
I also encountered the same problem. After upgrading to the latest versions of comfyui and Aux, I can now function normally

**Comment by nakanakapoi** [comment]
I got the same problem in standalone windows version. Updating does not fix it. I guess this is due to conflict with other custom nodes. In my case it is "was node suite". 

Removing this node afterward does not fix it either. Only when I restore my backup without this node installed that this error disappears.

Curiously, this only happen to one particular machine. I have other machines that have both nodes and they run just fine.

**Comment by Gerkinfeltser** [comment]
I was having this issue as well. But after removing the `.......\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cv2` dir & replacing it with a near-vanilla version of comfyui portable I am now able to use DW without issues.

I say "near-vanilla" because I did go ahead and install the manager, Inspire, Impact, & this extension and now the DWPreprocessor doesn't result in an error anymore. I'm not sure which package provides the cv2 stuff so I just installed the items that seemed necessary to use said functionality.

**Comment by leleneb** [comment]
I have the same issue, installing the [ComfyUI Impact Pack] via the manager fixe the problem for me.
Thx @Gerkinfeltser  for the tips !

**Comment by abexvfx** [comment]
same here! i did everything! nothing

**Comment by abexvfx** [comment]
> I have the same issue, installing the [ComfyUI Impact Pack] via the manager fixe the problem for me. Thx @Gerkinfeltser for the tips !

how did you fix it?

**Comment by mihicherub** [comment]
> I was having this issue as well. But after removing the `.......\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cv2` dir & replacing it with the cv2 dir of a near-vanilla version of from comfyui portable, I am now able to use DW without issues.
> 
> I say "near-vanilla" because I did go ahead and install the manager, Inspire, Impact, & this extension in that version I took the cv2 dir and now the DWPreprocessor doesn't result in an error anymore. I'm not sure which package provides the cv2 stuff so I just installed the items that seemed necessary to use said functionality.

removed comfyui cv2 and paste it with the "...\stable-diffusion-webui\venv\Lib\site-packages" cv2 folder. problem fixed. thanks
