### ISSUE TITLE
When does your assembly support Instant ID?

### ISSUE THREAD

**Issue by usaking12** [Fannovel16/comfyui_controlnet_aux#239]
https://github.com/Mikubill/sd-webui-controlnet/discussions/2589
[1.1.439] Instant ID

At present, there are always problems in the operation of other related nodes or the generation speed is slow, webu-ControlNet is better to understand and maintain, and I hope the controlnet_aux under comfyui can also be well supported.
Instant ID's simulation of the face is really beyond imagination, especially the side face, etc., the preprocessor to locate the face is first seen.

Expect the Great God to support or better

目前其他人的相关节点操作上总是有问题或生成速度慢，webui-controlnet使用上好理解维护，希望comfyui下的controlnet_aux也能很好的支持。
Instant ID对脸部模拟的确超乎想象，尤其是侧脸等，定位脸部的预处理器第一次见到。

期待大神能支持或更好

**Comment by Fannovel16** [comment]
This extension only supports image-outputting CN preprocessors. Fortunately, there is a decent implementation of InstantID on ComfyUI: https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID
