### ISSUE TITLE
Can I color gray and white photos using controlnet recolor preprocessor in comfyui through this plugin？

### ISSUE THREAD

**Issue by GoodGoodstudy0daydayup** [Fannovel16/comfyui_controlnet_aux#240]
<img width="623" alt="3add2117d2a60b9e4b6c877660583d5" src="https://github.com/Fannovel16/comfyui_controlnet_aux/assets/33535046/10908f80-48dc-48c6-ac78-b4d0176509d4">

**Comment by Fannovel16** [comment]
@GoodGoodstudy0daydayup Added
![](https://raw.githubusercontent.com/Fannovel16/comfyui_controlnet_aux/main/examples/example_recolor.png)

**Comment by GoodGoodstudy0daydayup** [comment]
Thank you so much,great job
