### ISSUE TITLE
Support providers on the MeshGraphormer node

### ISSUE THREAD

**Issue by aalmada** [Fannovel16/comfyui_controlnet_aux#244]
First off, a huge thank you for the fantastic work on this package, especially the MeshGraphormer node!

I've encountered an issue with the node related to hand detection. Currently, the detection fails frequently when hands are not open and isolated. Rather than requesting an improvement in detection, I'd like to suggest a different approach: allowing users to provide their own hand detection algorithm through a provider. This would potentially relieve you from the burden of handling detection intricacies.

I've noticed a similar implementation in the ImpactPack's FaceDetailer, where external providers can be seamlessly integrated. Implementing a similar approach for the MeshGraphormer node could offer users more flexibility and customization in their hand detection processes.

**Comment by alessandroperilli** [comment]
I second this suggestion. 

Here's an example, where the MeshGraphormer node fails to detect hands in one image and mis-detect one hand in another image:

<img width="1369" alt="Screenshot 2024-02-18 at 08 23 55" src="https://github.com/Fannovel16/comfyui_controlnet_aux/assets/9775949/f3229033-88f1-4f38-9aa7-152d411f148f">

However, passing the first image through the Hand Refiner pipeline of my AP Workflow for ComfyUI, which uses ImpactPack's FaceDetailer, leads to perfect detection and high-quality hand anatomy:

<img width="1677" alt="Screenshot 2024-02-18 at 08 32 22" src="https://github.com/Fannovel16/comfyui_controlnet_aux/assets/9775949/7c2a51f9-79c0-4b8b-a1f8-3a62735252e5">

<img width="742" alt="Screenshot 2024-02-18 at 08 32 52" src="https://github.com/Fannovel16/comfyui_controlnet_aux/assets/9775949/4e4b80c7-1fcc-4464-b34a-ba4f7cc2e6c1">

**Comment by Fannovel16** [comment]
@alessandroperilli The detector node get bounding box of each hand then pass one-by-one to MeshGraphormer right?

**Comment by alessandroperilli** [comment]
That's my assumption, yes. I didn't check what happens at the code level, but that's what I believe it happens in this first part of the workflow:

<img width="1081" alt="Screenshot 2024-05-01 at 15 21 30" src="https://github.com/Fannovel16/comfyui_controlnet_aux/assets/9775949/4066f973-631f-496b-a13c-5d22980ee4e5">

Happy to provide more details (or do tests) on Discord (Banodoco server or direct message) if you need. Look for `@perilli`

**Comment by Fannovel16** [comment]
@aalmada @alessandroperilli Here we go. This node supports batching out-of-the-box
![MeshGraphormer+ImpactPackDetector](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/16047777/502bc930-3631-4eab-be2d-dc1ad7d88622)

**Comment by alessandroperilli** [comment]
It works great, thank you!
