### ISSUE TITLE
TEED preprocessor node problem (probably model loading): [WinError 206] The filename or extension is too long:

### ISSUE THREAD

**Issue by Cedri4** [Fannovel16/comfyui_controlnet_aux#246]
Running the portable version using the latest comfyui and custom nodes version

On comfyui I got that error
Error occurred when executing TEEDPreprocessor:

[WinError 206] The filename or extension is too long: 'F:\\Stable-Diffusion\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\ckpts\\bdsqlsz/qinglong_controlnet-lllite\\cache\\models--bdsqlsz--qinglong_controlnet-lllite\\snapshots\\e51c0770bd1ec5cf6419a7e0692e57d7ed5abe23\\Annotators'

File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 372, in new_func
res_value = old_func(*final_args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\teed.py", line 19, in execute
model = TEDDetector.from_pretrained().to(model_management.get_torch_device())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\teed\__init__.py", line 25, in from_pretrained
model_path = custom_hf_download(pretrained_model_or_path, filename, subfolder="Annotators")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\util.py", line 264, in custom_hf_download
model_path = hf_hub_download(repo_id=pretrained_model_or_path,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^
File "F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1390, in hf_hub_download
os.makedirs(os.path.dirname(pointer_path), exist_ok=True)
File "", line 225, in makedirs

I tried using the perfect resolution on the AIO nodes, and the normal node but I still got that error.

**Comment by Layer-norm** [comment]
The max_path length in windows is 260. 
[7_model.pth](https://huggingface.co/bdsqlsz/qinglong_controlnet-lllite/blob/main/Annotators/7_model.pth) needs **11** and  your path `'F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\bdsqlsz/qinglong_controlnet-lllite\cache\models--bdsqlsz--qinglong_controlnet-lllite\snapshots\e51c0770bd1ec5cf6419a7e0692e57d7ed5abe23\Annotators'` takes **249**, but we need a extra slashe '\\' here. 

**11+249+1=261 > 260**, That's why this error occur.

Maybe, you can rename the folders in a shorter way and try again. 
Or you can download the [model](https://huggingface.co/bdsqlsz/qinglong_controlnet-lllite/blob/main/Annotators/7_model.pth) directly and put that into `'F:\Stable-Diffusion\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\bdsqlsz\qinglong_controlnet-lllite\'` folder.

**Comment by Cedri4** [comment]
I tried renaming the folder and installing the model and still it ain't working

**Comment by Layer-norm** [comment]
Let's try this way:
First, Hold "windows buton" and press "R" on your keyboard to open the **Run Command box**
then type "gpedit.msc" and press "ok".After that you will get into the **Group Policy Editor**
![1](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/140777998/52735a2f-79c1-46bf-84b9-5ed3e6609565)
Second, find the `Enable Win32 long paths` which belong in `Computer Configuration > Administrative Templates > System > Filesystem > Enable Win32 long paths` . Double-click it.

![2](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/140777998/dee09a8b-3271-4608-a139-1ededa8adfd0)

![3](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/140777998/b491d707-921e-4ca7-9f4b-339e74dafb60)
Finally, enable this setting, apply it and press 'ok', then you path limit will gone.

![4](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/140777998/f63c1b0a-df8d-4235-a4c6-70351b6af431)

**Comment by Cedri4** [comment]
Still ain't working I tried this technique, and after the renaming technique.

**Comment by Cedri4** [comment]
Is there a way to use the downloaded model instead the downloaded using the huggingface model with the long path?

**Comment by Cedri4** [comment]
Here is my gpedit setting (I am on Windows 11 so I don't know if that is the reason it don't works)
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/93396286/42a2a108-22f9-4c60-8d19-ea1c057bbac2)

**Comment by Layer-norm** [comment]
> Is there a way to use the downloaded model instead the downloaded using the huggingface model with the long path?
yes, you can **create** a file named `config.yaml` to move the **ckpts** folder.
for example, if I put **ckpts** in Disk I,
![a](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/140777998/784c2d66-9647-4d65-b6c3-ffea807de911)

and I will create `config.yaml` in the comfyui_controlnet_aux folder like this:
![b](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/140777998/6edb91c4-a7f3-4265-9739-50d28a9fe91c)
Then, all models will download into `I:\\ckpts` folder.
![c](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/140777998/602ecdc7-ddf5-4b5c-acb2-e1142d5bdbd4)

**Comment by Layer-norm** [comment]
What's more, you can dowload models from huggingface:
![e](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/140777998/345f1d0a-3f36-4e1f-a231-ddf2df70c476)
For example, the model url is https://huggingface.co/bdsqlsz/qinglong_controlnet-lllite/blob/main/Annotators/7_model.pth.
you can replace `https://huggingface.co` to your **ckpts** path (like me is `I:\\ckpts`), then delete `/blob/main`.

that will be the model path. namely: `I:\\ckpts\\bdsqlsz\\qinglong_controlnet-lllite\\Annotators\\7_model.pth`

**Comment by Cedri4** [comment]
Thank you so much, it works amazingly well!
