### ISSUE TITLE
[Feature Request] Download models to comfy's "models/controlnet/preprocessors" folder, not into custom nodes folder

### ISSUE THREAD

**Issue by unLomTrois** [Fannovel16/comfyui_controlnet_aux#247]
I have a lot of models in my A1111 setup, and I would like to avoid duplicating these heavy models on all my hard drives.
It would be nice if they were loaded into a folder like "models/controlnet/preprocessors".

**Comment by Layer-norm** [comment]
https://github.com/Fannovel16/comfyui_controlnet_aux/issues/246#issuecomment-1937050904
https://github.com/Fannovel16/comfyui_controlnet_aux/issues/246#issuecomment-1937054603
