### ISSUE TITLE
It seems that comfyui-reactor-node, ComfyUI_LayerStyle, and comfyui_controlnet_aux, the three plugins, cannot work together perfectly no matter what. The issue lies in the opencv dependency package.

### ISSUE THREAD

**Issue by wibur0620** [Fannovel16/comfyui_controlnet_aux#252]
No matter how I adjust the version of the opencv dependency package, the three plugins, comfyui-reactor-node, ComfyUI_LayerStyle, and comfyui_controlnet_aux, cannot work together simultaneously. For more details, please refer to https://github.com/chflame163/ComfyUI_LayerStyle/issues/5.

**Comment by Layer-norm** [comment]
It seems that they sloved this issue. 
Please update your comfyui-reactor-node and make sure your **opencv-python**, **opencv-contrib-python**, **opencv-python-headless** and **opencv-contrib-python-headless** are in the same version.
