### ISSUE TITLE
node conflict

### ISSUE THREAD

**Issue by loOong-Cheng** [Fannovel16/comfyui_controlnet_aux#260]
I have the latest version of comfy ui. Does anyone know why it has conflict with core inference node?
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/21363951/10b64eed-e1f9-4e40-a86b-3288548bb5fc)

**Comment by Layer-norm** [comment]
Because they copied our code and hadn't renamed nodes.
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/140777998/3a73c978-bcd4-4feb-af12-f66c2075da03)
