### ISSUE TITLE
First time using, getting errors: Error occurred when executing MiDaS-DepthMapPreprocessor

### ISSUE THREAD

**Issue by GhostBat101** [Fannovel16/comfyui_controlnet_aux#261]
Error occurred when executing MiDaS-DepthMapPreprocessor:

[Errno 2] No such file or directory: 'F:\\ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\ckpts\\lllyasviel/Annotators\\cache\\models--lllyasviel--Annotators\\blobs\\501f0c75b3bca7daec6b3682c5054c09b366765aef6fa3a09d03a5cb4b230853.incomplete'

It's not just with this, same thing happening with any other preprocessor, any solution?

**Comment by GhostBat101** [comment]
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/77197454/b7fe487b-3dbd-4ae3-8621-303ef7d58bb9)
here's what the error looks like for any preprocessor, not just midas.

**Comment by Fannovel16** [comment]
Move to https://github.com/Fannovel16/comfyui_controlnet_aux/issues/264
