### ISSUE TITLE
Support Depth_fm

### ISSUE THREAD

**Issue by sdbds** [Fannovel16/comfyui_controlnet_aux#282]
https://github.com/CompVis/depth-fm

**Comment by Fannovel16** [comment]
Eh I don't want to touch diffusers stuff but someone ported it to Comfy: https://github.com/kijai/ComfyUI-depth-fm

**Comment by Fannovel16** [comment]
@sdbds You may find this interesting btw: https://github.com/kijai/ComfyUI-Geowizard. It's more consistent than DepthFM and can give some pretty good result with just 4 steps + DEIS scheduler
