### ISSUE TITLE
[ Request ] Preprocessor Selector 

### ISSUE THREAD

**Issue by JorgeR81** [Fannovel16/comfyui_controlnet_aux#289]
The AIO Aux Preprocessor node is very useful !

If possible could you also add a dedicated preprocessor selector ?

Now can connect the AIO Aux Preprocessor to a primitive. 
But primitives have limitations.
 
For instance, Anything Everywhere? does not work with primitives. 
And it's unlikely it ever will.
https://github.com/chrisgoringe/cg-use-everywhere?tab=readme-ov-file#primitives-and-combos-and-the-like

The rgthree suite has a similar selector, but for KSampler configuration.
This allows me to use the same sampler and sheduler, throughout the workflow, via AE nodes. 

Now, I can also use AE nodes to set the ControlNet model, throughout the workflow.  
Because the "vanilla" [ Load ControlNet Model ] node also works with AE.

It would be great to do the same with the ControlNet Preprocessor !

![cn](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/72734038/cd30a57d-9965-48da-b53c-eeb8866719d0)

**Comment by Layer-norm** [comment]
The preprossor is a custom value and it cannot use that with AE, but you can use the `CR String To Combo` node from [ComfyUI_Comfyroll_CustomNodes](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes) to use AE like this:
![selector](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/140777998/df1a5549-704a-4fea-8198-087b6ecf3850)

**Comment by JorgeR81** [comment]
OK, thanks for the tip !
