### ISSUE TITLE
why not support reference Controlnet?

### ISSUE THREAD

**Issue by jax-explorer** [Fannovel16/comfyui_controlnet_aux#294]
Would you consider supporting reference controlnet? reference controlnet is very useful in resolving inconsistencies in composition but consistency in roles.

**Comment by Fannovel16** [comment]
This repo only supports model generating hint images (e.g. depth map, Canny edge, OpenPose skeleton, etc). You can get proper Reference CN implementation in ComfyUI from https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet
