### ISSUE TITLE
reason for using custom_mmpkg?

### ISSUE THREAD

**Issue by bluelocate** [Fannovel16/comfyui_controlnet_aux#30]
Hello I have a question about using custom_mmpkg.
In src folder, it using 'custom_mmpkg/mmcv'  why embedding this in src instead like 'pip install mmcv'?
because of embedded in src folder I have an issue of conflict mmcv version in another module file in custom_nodes

**Comment by Fannovel16** [comment]
Can you post the full log? I think I screw up the sys.path somewhere in the code as I made "custom_mmpkg" just for avoiding conflicts lol.

**Comment by bluelocate** [comment]
Traceback (most recent call last):
  File "/home/workspace/ComfyUI/nodes.py", line 1513, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/workspace/ComfyUI/custom_nodes/my_custom_node.py", line 101, in <module>
    from mmdet.apis import (inference_detector, init_detector)
  File "/usr/local/lib/python3.10/site-packages/mmdet/__init__.py", line 17, in <module>
    and mmcv_version < digit_version(mmcv_maximum_version)), \
AssertionError: MMCV==1.3.17 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.

Cannot import /home/workspace/ComfyUI/custom_nodes/my_custom_node.py module for custom nodes: MMCV==1.3.17 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.


Error log is like this. It's because my_custom_node.py has `import mmcv` but it's try to use  `src.custom_mmpkg.mmcv`
I resolve this issue just remove `src/custom_mmpkg/mmcv` :)

**Comment by Fannovel16** [comment]
@bluelocate I pushed a mass rename from `src.custom_mmpkg.mmcv` to `src.custom_mmpkg.custom_mmcv` and `src.custom_mmpkg.mmseg` to ``src.custom_mmpkg.custom_mmseg`. Can you try it again?

**Comment by bluelocate** [comment]
@Fannovel16 Oh it works well :) Thank you for fixing
