### ISSUE TITLE
ControlNet++

### ISSUE THREAD

**Issue by vbqgyy** [Fannovel16/comfyui_controlnet_aux#309]
https://github.com/liming-ai/ControlNet_Plus_Plus
I see this, seems to work well, it is possible to add this extension？

**Comment by Fannovel16** [comment]
This repo is just for ControlNet preprocessors. You can just download the files (HF weights) and place them into models/ControlNet folder

**Comment by vbqgyy** [comment]
That would be great. Thank you.
