### ISSUE TITLE
【request】Can preprocessors be integrated into a single node？

### ISSUE THREAD

**Issue by amimi818** [Fannovel16/comfyui_controlnet_aux#31]
Is it possible to integrate the preprocessors into a single node? Switch preprocessors by selecting in the node. This would allow for ease of use and reduce the number of nodes in the workflow.

**Comment by youyegit** [comment]
The same need. It will be convenient to choose what to use.

**Comment by Fannovel16** [comment]
@amimi818 @youyegit It is implemeted.

**Comment by youyegit** [comment]
A great job .  Could it add two options  that be called "Invert" and "None" which invert the image or just return the orginal image ?
In this case users don't need to switch it when inputting other image .

**Comment by amimi818** [comment]
great！

**Comment by amimi818** [comment]
> A great job . Could it add two options that be called "Invert" and "None" which invert the image or just return the orginal image ? In this case users don't need to switch it when inputting other image . ![image](https://user-images.githubusercontent.com/131540443/266770853-f4fc6f73-78ff-4cce-ad51-722ef68dd7dc.png)

good idea. Before that ，you can use “bypass" to do it.

**Comment by xueqing0622** [comment]
> A great job . Could it add two options that be called "Invert" and "None" which invert the image or just return the orginal image ? In this case users don't need to switch it when inputting other image . ![image](https://usercontent.githubfast.com/private-user-images/131540443/266770853-f4fc6f73-78ff-4cce-ad51-722ef68dd7dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4OTIyOTUsIm5iZiI6MTcwMjg5MTk5NSwicGF0aCI6Ii8xMzE1NDA0NDMvMjY2NzcwODUzLWY0ZmM2ZjczLTc4ZmYtNGNjZS1hZDUxLTcyMmVmNjhkZDdkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwOTMzMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDJhNjBjZGYyODM1NTY5YjQ5ZmU2NjEwZDMwOWNjNDc4MjdmMzVlZTNiNzc2OTA1ZTE0MzJhNWY4NTBkYTk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cia6oREBatHm5BPErpAkHAKcp4vIGUvWjy0IAYphB0k)

Yes, "invert image" and "none" is good idea!
