### ISSUE TITLE
Depend on headless version of opencv-python

### ISSUE THREAD

**Issue by oxc** [Fannovel16/comfyui_controlnet_aux#312]
opencv-python (and opencv-python-contrib) provide both a desktop and a headless version. The headless version is a drop-in replacement for the full version, when methods like `cv2.imgshow` are not needed. AFAICT, none of those methods should be called by this extension.

From the documentation: https://pypi.org/project/opencv-python-headless/#installation-and-usage

> b. Packages for server (headless) environments (such as Docker, cloud environments etc.), no GUI library dependencies

> 
> These packages are smaller than the two other packages above because they do not contain any GUI functionality (not compiled with Qt / other GUI components). This means that the packages avoid a heavy dependency chain to X11 libraries and you will have for example smaller Docker images as a result. You should always use these packages if you do not use cv2.imshow et al. or you are using some other package (such as PyQt) than OpenCV to create your GUI.
> 
> * Option 3 - Headless main modules package: pip install opencv-python-headless
> * Option 4 - Headless full package (contains both main modules and contrib/extra modules): pip install opencv-contrib-python-headless (check contrib/extra modules listing from [OpenCV documentation](https://docs.opencv.org/master/))

AFAICT, the desktop version is not needed for this package. Switching to the headless version would also reduce friction with other packages due to package version mismatch, that people have been reporting.

**Comment by otjamin** [comment]
I would like to reopen this issue since the dependency has been changed back in c97481a14645c8b2e44cd472422eb3e3bc8362ef. Is there a reason for this @Fannovel16 ?
