### ISSUE TITLE
openpose json data

### ISSUE THREAD

**Issue by BurningSpy** [Fannovel16/comfyui_controlnet_aux#32]
Hi, 

Would it be possible to also output the openpose json data?

I would sometimes like to adjust the detected pose when it gets something wrong in the openpose editor, but currently I can only estimate and rebuild the pose from the image. 

Thanks in advance!

**Comment by Fannovel16** [comment]
@BurningSpy I just added Openpose JSON in Openpose and DWPose nodes' outputs. Check [here](https://github.com/Fannovel16/comfyui_controlnet_aux#faces-and-poses).
