### ISSUE TITLE
which preprocessor in ComfyUI matches the option of "scribble_pidinet" in SD WebUI

### ISSUE THREAD

**Issue by hawanlee** [Fannovel16/comfyui_controlnet_aux#320]
which preprocessor in ComfyUI matches the option of "scribble_pidinet" in SD WebUI? 
THX

**Comment by Fannovel16** [comment]
Oh I haven't implemented that

**Comment by hawanlee** [comment]
Thank you for the quick update. 
However, I noticed that there are some differences between the line drafts generated by the webui and your node. 
The original image and the line drafts results are as follows:
**Input Image:**
![refe](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/36850862/9f5563a2-430f-47f3-9771-2a764f1c11c3)
**WebUI "scrible_pidinet" result:**
![webui-pidinet](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/36850862/9b12b7cb-e5d7-4127-b250-d663b3f6f52a)
 **"Scribble PiDiNet Lines" result:**
![ComfyUI_scrible_pidinet](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/36850862/077a871e-eaa1-4ab0-a7d8-c18cadeff4f5)
