### ISSUE TITLE
No module named 'controlnet_aux.depth_anything'

### ISSUE THREAD

**Issue by blueroutecn** [Fannovel16/comfyui_controlnet_aux#325]
![截图 2024-05-04 16-20-46](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/12109789/9fff1f47-0447-4181-932a-c822d4a28cf7)

!!! Exception during processing!!! No module named 'controlnet_aux.depth_anything'
Traceback (most recent call last):
  File "/home/llm/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/llm/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/llm/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/llm/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/depth_anything.py", line 17, in execute
    from controlnet_aux.depth_anything import DepthAnythingDetector
ModuleNotFoundError: No module named 'controlnet_aux.depth_anything'

### ComfyUI Revision: 2276 [80ae4c09] | Released on '2024-05-04'

How to fix it.

**Comment by zhouker1020** [comment]
me too

**Comment by pandadgb** [comment]
me too

**Comment by bonecast** [comment]
i cant find the solution anywhere

**Comment by wangwangchao123** [comment]
My guess is ”depth anything vitl14.pth” The location of the file is wrong, but I don't know how to solve it. Please help me if anyone has solved it.

**Comment by 0utsider0** [comment]
same problem here

**Comment by Fannovel16** [comment]
Fixed in
