### ISSUE TITLE
Does the one with more control modes have nodes? Where can I set them?

### ISSUE THREAD

**Issue by zhaowolf** [Fannovel16/comfyui_controlnet_aux#329]
### More Control Modes (previously called Guess Mode)  
更多控制模式（以前​​称为猜测模式）

We have fixed many bugs in previous 1.0’s Guess Mode and now it is called Control Mode  
我们修复了之前1.0的猜测模式中的许多错误，现在称为控制模式

![image](https://user-images.githubusercontent.com/19834515/236641759-6c44ddf6-c7ad-4bda-92be-e90a52911d75.png)

Now you can control which aspect is more important (your prompt or your ControlNet)：  
现在您可以控制哪个方面更重要（您的提示或您的 ControlNet）：

* "Balanced": ControlNet on both sides of CFG scale, same as turning off "Guess Mode" in ControlNet 1.0  
  “平衡”：CFG 刻度两侧的 ControlNet，与关闭 ControlNet 1.0 中的“猜测模式”相同
* "My prompt is more important": ControlNet on both sides of CFG scale, with progressively reduced SD U-Net injections (layer_weight\*=0.825\*\*I, where 0<=I <13, and the 13 means ControlNet injected SD 13 times). In this way, you can make sure that your prompts are perfectly displayed in your generated images.  
  “我的提示更重要”：CFG规模两侧的ControlNet，逐渐减少SD U-Net注入（layer_weight\*=0.825\*\*I，其中0<=I <13，13表示ControlNet注入SD 13次）。通过这种方式，您可以确保您的提示完美地显示在生成的图像中。
* "ControlNet is more important": ControlNet only on the Conditional Side of CFG scale (the cond in A1111's batch-cond-uncond). This means the ControlNet will be X times stronger if your cfg-scale is X. For example, if your cfg-scale is 7, then ControlNet is 7 times stronger. Note that here the X times stronger is different from "Control Weights" since your weights are not modified. This "stronger" effect usually has less artifact and give ControlNet more room to guess what is missing from your prompts (and in the previous 1.0, it is called "Guess Mode").  
  “ControlNet 更重要”：ControlNet 仅在 CFG 规模的条件侧（A1111 的 batch-cond-uncond 中的 cond）。这意味着如果您的 cfg-scale 为 X，则 ControlNet 的强度将增强 X 倍。例如，如果您的 cfg-scale 为 7，则 ControlNet 的强度将增强 7 倍。请注意，此处的 X 倍强度与“控制重量”不同，因为您的重量没有修改。这种“更强”的效果通常具有更少的伪影，并为 ControlNet 提供更多空间来猜测提示中缺少的内容（在之前的 1.0 中，称为“猜测模式”）。

**Comment by Fannovel16** [comment]
@zhaowolf The custom node `Scaled Soft Weight` from [ComfyUI-Advanced-ControlNet](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet)
 is the equalvement of  "My prompt is more important" option
