### ISSUE TITLE
MeshGraphormerDetector.from_pretrained() got an unexpected keyword argument 'detect_thr'

### ISSUE THREAD

**Issue by zulfadzlie** [Fannovel16/comfyui_controlnet_aux#339]

**Comment by bardbit** [comment]
hello, did you find the cause or solution to this problem? I have exactly the same error

**Comment by zulfadzlie** [comment]
> hello, did you find the cause or solution to this problem? I have exactly the same error

I realized that the node that I was using was deprecated. I switched to the latest node of the same type and got no errors.
