### ISSUE TITLE
Canny line is blurred

### ISSUE THREAD

**Issue by liulsg** [Fannovel16/comfyui_controlnet_aux#34]
The lines processed by Canny are blurred and unclear, and neither enlarging the original image nor modifying the size can change the result

**Comment by Fannovel16** [comment]
Fixed at https://github.com/Fannovel16/comfyui_controlnet_aux/commit/171a4a46010aa47856b5a452eccd20054226b2e6 + https://github.com/Fannovel16/comfyui_controlnet_aux/commit/46f5d5ac72c5ee0b7661fab81e2dfb992a82c24a
