### ISSUE TITLE
[FeatureRequest] New preprocessor Depth and Normal Metric3D

### ISSUE THREAD

**Issue by sdbds** [Fannovel16/comfyui_controlnet_aux#343]
https://github.com/YvanYin/Metric3D

**Comment by wibur0620** [comment]
https://github.com/TheMistoAI/ComfyUI-Anyline

**Comment by wibur0620** [comment]
> https://github.com/TheMistoAI/ComfyUI-Anyline

https://github.com/TheMistoAI/MistoLine

**Comment by Fannovel16** [comment]
@sdbds https://github.com/Fannovel16/comfyui_controlnet_aux/blob/main/examples/example_metric3d.png?raw=true

**Comment by Fannovel16** [comment]
@wibur0620 ![](https://raw.githubusercontent.com/Fannovel16/comfyui_controlnet_aux/main/examples/example_anyline.png)

**Comment by wibur0620** [comment]
https://github.com/Fannovel16/comfyui_controlnet_aux/assets/131615326/42df065a-094f-4699-a79c-3cb2dd22a358



> RepeatImageBatch is unneccessary. It's there for testing multiple batches

This is strange. This node is indeed confirmed to be yours, but the way it opens feels very strange to me. I did not uninstall the ComfyUI-Anyline plugin before updating your plugin. I wonder if this is the reason for the issue?

**Comment by wibur0620** [comment]
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/131615326/5c0d02ac-aed1-439e-8f90-2a55aa579115)

**Comment by Fannovel16** [comment]
@wibur0620 Ah I forgot to change the category

**Comment by Fannovel16** [comment]
Fixed
https://github.com/Fannovel16/comfyui_controlnet_aux/commit/0c00bb6c4ceff64dd806d82d37b390914f214daf

**Comment by wibur0620** [comment]
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/131615326/6cd060b3-5f74-4a30-ab87-8d949a18a6d3)

**Comment by wibur0620** [comment]
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/131615326/f6a7ed91-55ba-46b7-89a3-227d7fccd102)

**Comment by wibur0620** [comment]
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/131615326/9b995c24-7a55-4b29-aae3-5da65949d8fb)
Is the metric_depth_vit_giant2_800k.pth model necessary? I noticed that this model is very large, and it was not used in the official demo of Metric3D.
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/131615326/fd9dfdae-13dc-4c6b-82c6-a8338196511c)

**Comment by wibur0620** [comment]
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/131615326/f7c47c9d-1e30-4503-8fce-d0dd77516930)
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/131615326/4e1a2d52-5941-4d0e-82cb-72709e7ebc1a)

**Comment by Fannovel16** [comment]
@wibur0620 I add that for versatility. I agree that the difference between small and large is marginal tho

**Comment by Fannovel16** [comment]
https://github.com/Fannovel16/comfyui_controlnet_aux/commit/ab0705c9e3ae50e3cd58f339578013241acf4659

**Comment by wibur0620** [comment]
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/131615326/36a339ab-2cda-4122-8664-c8052c90e930)
This issue seems to remain unresolved; there is a bug in the deep preprocessing.

**Comment by Fannovel16** [comment]
@wibur0620 Wdym?

**Comment by wibur0620** [comment]
> @wibur0620 Wdym?

After processing through this node, the resulting image is completely white and lacks any depth information, regardless of which model I choose.

**Comment by Fannovel16** [comment]
@wibur0620 Y

> > @wibur0620 Wdym?
> 
> After processing through this node, the resulting image is completely white and lacks any depth information, regardless of which model I choose.

What about normal?

**Comment by sdbds** [comment]
> > @wibur0620 Wdym?
> 
> After processing through this node, the resulting image is completely white and lacks any depth information, regardless of which model I choose.

same problem.

**Comment by Fannovel16** [comment]
@sdbds @wibur0620 
![example_metric3d](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/16047777/57fb7a5b-e628-4a37-9076-b765be2efd8f)

**Comment by sdbds** [comment]
> @sdbds @wibur0620 ![example_metric3d](https://private-user-images.githubusercontent.com/16047777/331878745-57fb7a5b-e628-4a37-9076-b765be2efd8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxODQ4NTUsIm5iZiI6MTcxNjE4NDU1NSwicGF0aCI6Ii8xNjA0Nzc3Ny8zMzE4Nzg3NDUtNTdmYjdhNWItZTYyOC00YTM3LTkwNzYtYjc2NWJlMmVmZDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDA1NTU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3Njk0OTRhZTdmNTNlMmVlMTIwYTdkMGRkMjUxZDU0YmNkYjQ5YTUwYmFhODE0YzcyMGRhNmZjZDc5ODhkNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zr-tSId6aAb6LnR5g15xHDhODD4J7cfPzqRyAYljRaY)

![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/8085926/eafcf17c-fc0c-4135-9a3b-466d0957522c)


it works now

**Comment by rethink-studios** [comment]
Just downloaded and tried to use the Metric3D-DepthMapPreprocessor and got this error.
I created the folders needed, downloaded the file, and I still get the error

![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/60104539/73fbeb61-4f5c-459a-9c20-3d500dd60761)

![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/60104539/d16b5329-a593-4f17-befb-f3138b11919c)

![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/60104539/44d95bce-5044-4ca0-b168-119f305fd763)

**Comment by rethink-studios** [comment]
> ![image](https://private-user-images.githubusercontent.com/131615326/331821102-6cd060b3-5f74-4a30-ab87-8d949a18a6d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjAwMDEsIm5iZiI6MTcxNjIxOTcwMSwicGF0aCI6Ii8xMzE2MTUzMjYvMzMxODIxMTAyLTZjZDA2MGIzLTVmNzQtNGEzMC1hYjg3LThkOTQ5YTE4YTZkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQxNTQxNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzYzMTYzNmJlMDIzYWQzNjk3MzQxNGM3ZjczOGFjNWRhYWQwY2Y0NGFkMjRhOGVkNjJmN2FhNjE5NzcwM2YyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CLPeQSrUcaIYMdPNAhark09Pjw8tSDBdjgjrMaIzdzA)

I got the same error (10:45 CST)

**Comment by rethink-studios** [comment]
link changed??
Here's the working link:
https://huggingface.co/JUGGHM/Metric3D/resolve/main/metric_depth_vit_giant2_800k.pth?download=true

**Comment by kagevazquez** [comment]
Error occurred when executing Metric3D-NormalMapPreprocessor:

Failed to find function: controlnet_aux.metric3d.mono.model.backbones.vit_giant2_reg


![Screenshot 2024-05-22 164130](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/1572367/1beaebe4-95a2-4ee8-b0e1-e8bb7c613687)
