### ISSUE TITLE
ModuleNotFoundError: No module named 'controlnet_aux.tile'

### ISSUE THREAD

**Issue by metahades18892** [Fannovel16/comfyui_controlnet_aux#361]
I Have this error: 

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
# 😺dzNodes: LayerStyle -> Warning: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
got prompt
[rgthree] Using rgthree's optimized recursive execution.
[rgthree] First run patching recursive_output_delete_if_changed and recursive_will_execute.
[rgthree] Note: If execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI.
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
Using pytorch attention in VAE
Using pytorch attention in VAE
[AnimateDiffEvo] - INFO - Loading motion module hotshotxl_mm_v1.pth via Gen2
INFO: Clip Vision model loaded from C:\Users\kevin\Desktop\ComfyUI\ComfyUI\models\clip_vision\CLIP-ViT-H-14-laion2B-s32B-b79K.safetensors
!!! Exception during processing!!! IPAdapter model not found.
Traceback (most recent call last):
  File "C:\Users\kevin\Desktop\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kevin\Desktop\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kevin\Desktop\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 515, in load_models
    raise Exception("IPAdapter model not found.")
Exception: IPAdapter model not found.

Prompt executed in 242.52 seconds
FETCH DATA from: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
# 😺dzNodes: LayerStyle -> Warning: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 84, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto
got prompt
[rgthree] Using rgthree's optimized recursive execution.
INFO: IPAdapter model loaded from C:\Users\kevin\Desktop\ComfyUI\ComfyUI\models\ipadapter\ip-adapter-plus_sdxl_vit-h.bin
INFO: the IPAdapter reference image is not a square, CLIPImageProcessor will resize and crop it at the center. If the main focus of the picture is not in the middle the result might not be what you are expecting.
Requested to load CLIPVisionModelProjection
Loading 1 new model
Requested to load SDXLClipModel
Loading 1 new model
!!! Exception during processing!!! No module named 'controlnet_aux.tile'
Traceback (most recent call last):
  File "C:\Users\kevin\Desktop\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kevin\Desktop\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kevin\Desktop\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 117, in execute
    return getattr(aux_class(), aux_class.FUNCTION)(**params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kevin\Desktop\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\tile.py", line 18, in execute
    from controlnet_aux.tile import TileDetector
ModuleNotFoundError: No module named 'controlnet_aux.tile'

Prompt executed in 99.01 seconds

![imagen](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/163777886/b4b1797f-055b-4821-b743-243c3b1905db)

**Comment by SKG-blood** [comment]
same problem

**Comment by rafstahelin** [comment]
I am also getting this issue when launching comfyui

**Comment by Fannovel16** [comment]
Fixed in https://github.com/Fannovel16/comfyui_controlnet_aux/commit/c47ccabe150aa9d4033a7154138ab82be306bd79

**Comment by Awaken-ai** [comment]
so what is the sollution. Can't find
