### ISSUE TITLE
Organize all the nodes included in Controlnet_aux under a single menu

### ISSUE THREAD

**Issue by StellarBeing25** [Fannovel16/comfyui_controlnet_aux#362]
It is very cumbersome to create a complex workflow in ComfyUI based on controlnet for the new users since they do not yet know the names of various nodes included in controlnet_aux, so they cannot instantly search the node; they have to go through various menus and submenus to find the desired node. It would be great if you could please organize all the included nodes under a single controlnet menu and submenus like preprocessors, loaders, etc., like how IP Adapter Plus has organized all its nodes under a single menu.

**Comment by Fannovel16** [comment]
@StellarBeing25 I believe the current menu is already good enough. The submenus can tell the functionality of their preprocessors. Also unlike IP Adapter Plus, I have about 20 preprocessors with different kind of outputs and putting all of them under a menu would be quite long

**Comment by Fannovel16** [comment]
Imo, a better idea is combination nodes - nodes that can load a ControlNet and its most commonly used preprocessor counterpart
