### ISSUE TITLE
AUX Tile model's options are very blurry.

### ISSUE THREAD

**Issue by Rkkss** [Fannovel16/comfyui_controlnet_aux#37]
Some downsampling comparisons to older controlNET repo. From Left to right, base image > value 1 > 2 > 3

New(AUX)
![new](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/127614350/fa26c2f3-9578-44bf-beb4-fa810a44a442)

Old

![old](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/127614350/a965c3cd-a559-47b4-a80c-c4541720581e)

As you can see, in old tile controlNet prep.  Pyrup_iters 1 = base image 
In Aux, 1 is slightly blurrier than base and actually closer to Pyrup_iters  2 in old preprocessor.

Also can we choose downsampling rate as decimal number?

**Comment by Fannovel16** [comment]
Fixed (to lazy to find the commit, just do `git pull`).

> Also can we choose downsampling rate as decimal number?
No but you can do so by using image-resizing nodes from other extensions
