### ISSUE TITLE
Request follow-up model support for depth_anythimg V2

### ISSUE THREAD

**Issue by alex13by** [Fannovel16/comfyui_controlnet_aux#383]
https://github.com/MackinationsAi/Upgraded-Depth-Anything-V2?tab=readme-ov-file

Although there is a support node for depth_anythimg V2 in controlnet, the model provided by this address performs better and is requested to be supported.

**Comment by Fannovel16** [comment]
@alex13by How do they perform better? The repo linked above seem to be a fork of the original repo with some new features. However, I don't see any line mentioning the difference between the original checkpoints and their checkpoints.

**Comment by alex13by** [comment]
> @alex13by How do they perform better? The repo linked above seem to be a fork of the [original repo](https://github.com/DepthAnything/Depth-Anything-V2) with some new features. However, I don't see any line mentioning the difference between the original checkpoints and their checkpoints.

I can't confirm which aspect is better, even if the independent gradio is installed there is no feedback on efficiency, but at least the model is half the size
