### ISSUE TITLE
Why do I have to download again every time I run it?

### ISSUE THREAD

**Issue by Yorha4D** [Fannovel16/comfyui_controlnet_aux#39]
I want to use local files instead of downloading them from Hugface every time. And after downloading hugface, it will be downloaded again. I don't understand why it is necessary to download so many duplicate models @Fannovel16

**Comment by green-anger** [comment]
I've tried this only once, so don't know if it downloads models every time. However, it saved it inside directory "ckpts/.../snapshots/..." which is deeply nested inside the node path and inside snapshots it created a directory with long random name. This is extremely inconvenient. Would be perfect if we could set a path to all models, similar to how we redirect comfy to a1111's model paths. The node doesn't seem to have a settings file and there's no mentioning of such settings in the readme.md.

**Comment by Yorha4D** [comment]
@green-anger This random code may be related to the network address (my home and company are not the same), and I have changed the code myself so that it can be used even without the network.
https://github.com/Fannovel16/comfyui_controlnet_aux/pull/29#issue-1876958013
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/116185401/973d86e2-e98d-4503-8c48-8a0069d6376e)

**Comment by youcanyoubing** [comment]
> 这个随机代码可能与网络地址有关（我家和公司不一样），我自己更改了代码，以便即使没有网络也可以使用。 [#29（评论）](https://github.com/Fannovel16/comfyui_controlnet_aux/pull/29#issue-1876958013) ![image](https://user-images.githubusercontent.com/116185401/266875957-973d86e2-e98d-4503-8c48-8a0069d6376e.png)

你好，如何使用本地的模型，我完全连不上拥抱脸了，只有之前下载的模型

**Comment by Fannovel16** [comment]
I think I should replace `huggingface_hub` with direct downloading 🤔. That library isn't compatible with all enviroments. But such change will require redownloading.

**Comment by donglsci** [comment]
> However, it saved it inside directory "ckpts/.../snapshots/..."  @[green-anger](https://github.com/green-anger)

thanks a lot, i copied these five files to that directory, happy to find them works well, and do not need to download them again.
(i also tried to put these files to the path of lllyasviel/Annotators and yzd-v/DWPose, but it did not worked, maybe due to the version difference. )

![000](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/12135008/3a9ed264-0e93-4da4-87e8-2943425bd5e3)

**Comment by suede299** [comment]
Still wish there was a version that could use local models.
I created a new folder like I said above and copied the 2 models from DWpose over, but it still connects to Hugface.
It's definitely not going to download every time, but it must be trying to access Hugface, doing version comparisons and whatnot. It takes many seconds before it starts processing, as it does very quickly when I have vpn on.

Translated with www.DeepL.com/Translator

**Comment by Yorha4D** [comment]
@youcanyoubing @donglsci @suede299 Based on the information I have collected, there are currently more than 20 countries that are unable to connect directly or at low speeds (<10kb). So for people in these countries, connecting to huggingface to download several gigabytes of files is 100% error reporting. Here is a local version that can be used。https://github.com/DorotaLuna/comfyui_controlnet_aux_stable

**Comment by Layer-norm** [comment]
@Yorha4D I've changed all functions used hf_hub_download. It won't downlod  models again.  Besides, if the dir already existent while models not, it won't cause load error any more. You can use my repo with `git clone -b download https://github.com/Layer-norm/comfyui_controlnet_aux.git`
Here are the log and workflow.
![log](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/140777998/e92227c0-fb8b-458e-a4d9-3e7e98997db3)
![test](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/140777998/bcd3aadc-3072-4981-ad6f-e7c991e45ef4)
