### ISSUE TITLE
Inpant Preprocesol added options

### ISSUE THREAD

**Issue by hben35096** [Fannovel16/comfyui_controlnet_aux#408]
I'm using the Inpant Preprocesol node for controlnet_union_sdxl_10_promax and I only get a black image.

![workflowcn2](https://github.com/user-attachments/assets/0efe6591-60b5-4fb3-9b6a-c5bec11dceff)
Unless:

![workflowcn3](https://github.com/user-attachments/assets/0b954bd0-d10e-4ab0-8d9f-ce129762050c)
I guess this should be Inpant Preprocesol when outputing, the channel problem of the image, can you add an option, or add a node to convert the channel?

**Comment by adbrasi** [comment]
my love, convert the image to rgb!

**Comment by 3blackbar** [comment]
He shouldnt my love, that should be handled internally
