### ISSUE TITLE
No module named 'controlnet_aux.depth_anything'

### ISSUE THREAD

**Issue by shamikct** [Fannovel16/comfyui_controlnet_aux#413]
### Discussed in https://github.com/Fannovel16/comfyui_controlnet_aux/discussions/412

<div type='discussions-op-text'>

<sup>Originally posted by **shamikct** July 23, 2024</sup>
While executing a ComfyUI workflow i get the following error for the `Depth Anything` node. 
I have tried to reinstall the entire package several time with and without the ComfyUI Manger, but to no avail. 

The quick fix is to append the dir path to `PYTHONPATH`, in my case `/mnt/vol1/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/`, however, the question remains. 

Version details
ComfyUI: 2390[14764a](2024-07-22)
Manager: V2.48

Here's the entire error: 

```py
Error occurred when executing DepthAnythingPreprocessor:

No module named 'controlnet_aux.depth_anything'

File "/mnt/vol1/ComfyUI/execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/mnt/vol1/ComfyUI/execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/mnt/vol1/ComfyUI/execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/mnt/vol1/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/depth_anything.py", line 17, in execute
from controlnet_aux.depth_anything import DepthAnythingDetector
```

</div>
@Fannovel16

**Comment by Fannovel16** [comment]
Fixed in https://github.com/Fannovel16/comfyui_controlnet_aux/commit/c47ccabe150aa9d4033a7154138ab82be306bd79
