### ISSUE TITLE
After comfyui is updated to the latest version, DWPOSE cannot be read and an error occurs

### ISSUE THREAD

**Issue by lanse6899** [Fannovel16/comfyui_controlnet_aux#434]
After comfyui is updated to the latest version, DWPOSE cannot be read and an error occurs
![微信截图_20240817112431](https://github.com/user-attachments/assets/fe8796ba-a814-4cf7-869c-824c964e8a03)
Maybe that's the reason, but I don't know how to solve it

**Comment by lanse6899** [comment]
![Uploading 微信截图_20240817112123.png…]()

**Comment by lanse6899** [comment]
![123](https://github.com/user-attachments/assets/6abfe199-0369-40eb-93a7-a782c007f0ae)

**Comment by Fannovel16** [comment]
Solved at https://github.com/Fannovel16/comfyui_controlnet_aux/commit/4cd233c5d7afe2e51bf57ee7a5ba7e6fcb9cbb22
