### ISSUE TITLE
Error occurred when executing ACN_AdvancedControlNetApply:  'ControlNet' object has no attribute 'latent_format'

### ISSUE THREAD

**Issue by 271845845** [Fannovel16/comfyui_controlnet_aux#440]
Error occurred when executing ACN_AdvancedControlNetApply:

'ControlNet' object has no attribute 'latent_format'

**Comment by Fannovel16** [comment]
@271845845 This issue is related to [Advanced ControlNet](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/issues) but to the best of my knowlegde, it's caused due to ComfyUI in your machine is too old. If the issue still presists after updating ComfyUI, please add a new issue to ACN
