### ISSUE TITLE
Some of preprocessors create maps with offset.

### ISSUE THREAD

**Issue by mav-rik** [Fannovel16/comfyui_controlnet_aux#45]
After around 07.09.2023 HED and Depth maps generated with offset, when used together with canny it results in doubled edges with offset.

It works well on commit `360fcefcff250e9245db9eede6515139ac5bb4e5`. The issue happens somewhere after that commit.

**Comment by liulsg** [comment]
I tested them all,  Three of them were cropped. （hed line | scribble lines | sam segmentor）
![workflow (1)](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/97494068/346607cb-7253-4cea-ba15-c848798f6be0)

**Comment by Fannovel16** [comment]
Oh nvm I can reproduce the bug now.

**Comment by Fannovel16** [comment]
@mav-rik @liulsg What commit do yall use? On the latest commit, I can only reproduce the bug when using HED.

**Comment by liulsg** [comment]
> @mav-rik@liulsg你们都用什么提交？在最近的提交中，我只能在使用HED时重现bug。

1.The resolution is 1024 x 1024

**Comment by liulsg** [comment]
> @mav-rik@liulsg你们都用什么提交？在最近的提交中，我只能在使用HED时重现bug。

1.The resolution is 1024 x 1024  2.ComfyUI Revision: 1439 [fb3b7282]  3.Cnt is the final version    4.I don't know what else I can submit to help you with your investigation

**Comment by liulsg** [comment]
@Fannovel16 1.The resolution is 1024 x 1024 2.ComfyUI Revision: 1439 [fb3b7282] 3.Cnt is the final version 4.I don't know what else I can submit to help you with your investigation

**Comment by Fannovel16** [comment]
@liulsg Can you send the image?

**Comment by liulsg** [comment]
@Fannovel16 
![1](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/97494068/77e7a84a-ca23-4785-979d-1394566e8ecf)

**Comment by Eagle07-Sudo** [comment]
In fact, there are problems as a whole.
I have tried numerous images and obtained the same result. Here is this image for demonstration: 

![Man+Grid_Test](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/54370316/c910bf99-1f42-473e-ac16-b4ceb916209f)

and I encountered three kind of issues:

1. A group that crops image.
2. A group that resized images with distortion.
3. A third group that generates errors and doesn't work at all.

![ComfyUI_temp_bmtdk_00006_](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/54370316/135f4b46-30fe-4ba1-a717-ab0c1af07585)
**First Group Example**

![ComfyUI_temp_pkhpv_00004_](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/54370316/a287a02d-ca64-420c-ac6b-b554337adfee)
**Second Group Exapmle**

Now, here is a list of preprocessors categorized based on their performance:

**Works Fine:** 
          Canny, Tile, InPaint, Color

**First Group:** HED Lines, COCO Seg, UniFormer Seg, Fake Scribble Lines.

**Second Group:**
          OpenPose, DWPose, BAE Normal, MiDaS Normal, MiDaS Depth, Zoe Depth, LeReS Depth, Manga LineArt, Normal LineArt, PiDiNet Lines, Shuffle, SAM seg, Semantic Seg, Binary Lines, Scribble Lines, XDoG Lines.

**Third Group:** 
          - ADE20K Seg: `Error occurred when executing AnimeLineArtPreprocessor: Sizes of tensors must match except in dimension 1. Expected size 7 but got size 6 for tensor number 1 in the list.`
          - Anime LineArt: `Error occurred when executing AnimeLineArtPreprocessor: Sizes of tensors must match except in dimension 1. Expected size 7 but got size 6 for tensor number 1 in the list.`
         
**Doesn't work at all:** 
         - MediPipe: `Error occurred when executing MediaPipe-FaceMeshPreprocessor: cannot import name 'builder' from 'google.protobuf.internal' (D:\AI\SD\ComfyUI_windows_portable\python_embeded\lib\site-packages\google\protobuf\internal\__init__.py) File `


The workaround is to use selective dimensions:
- selective sizes, like 2048x1024, 1024x1024, 1024x512, 512x512, work for the second group and the third group.
- selective sizes, like 512x512, 1024x512, work for the first group. Despite that 2048x1024, 1024x1024 doesn't work.

**Comment by Fannovel16** [comment]
@liulsg The webui extension doesn't have these problems right?

**Comment by Fannovel16** [comment]
Fixed at https://github.com/Fannovel16/comfyui_controlnet_aux/commit/171a4a46010aa47856b5a452eccd20054226b2e6 and https://github.com/Fannovel16/comfyui_controlnet_aux/commit/825f7c6cba4d3f76d1706d72a0db99607ace8a27

I'm hoping that upgrading protobuf won't create conflicts lol.

**Comment by liulsg** [comment]
> @liulsg The A1111 CN extension doesn't have these problems right?
> 
> Regard the MediaPipe problem, you can fix it by upgrading protobuf but I'll try to fix the version of package `mediapipe`.

There is no problem with the CNT on A1111, which is a 1.6 stable version.

**Comment by Eagle07-Sudo** [comment]
> Fixed at [171a4a4](https://github.com/Fannovel16/comfyui_controlnet_aux/commit/171a4a46010aa47856b5a452eccd20054226b2e6) and [825f7c6](https://github.com/Fannovel16/comfyui_controlnet_aux/commit/825f7c6cba4d3f76d1706d72a0db99607ace8a27)
> 
> I'm hoping that upgrading protobuf won't create conflicts.

Thank you.

The problem has been resolved for all the preprocessors except for **OpenPose, Sam Seg, Anime LineArt**, and in different manners of resizing.

![ComfyUI_temp_lsute_00001_](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/54370316/f6abb4fc-160b-49bb-a44f-f4e34356b1a7)
![ComfyUI_temp_qpmzj_00003_](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/54370316/4452efe9-5205-4221-be61-16a895699b78)
![ComfyUI_temp_qicgr_00002_](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/54370316/70d949ae-c686-494d-b2be-796baecc3973)

**Comment by Fannovel16** [comment]
@Eagle07-Sudo I added `Image.fromarray(detected_map).show("DWPose")` to both preprocessors to check if they saw the same thing
![test_pose_see](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/16047777/f220c77b-d311-4a42-9631-2f2d3bd87601)

Here is the result (it is similar to A1111 CN extension's internal image processing before feeding to preprocessors)
DWPose
![what_dwpose_see](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/16047777/ac357ac3-cbd7-4faa-ba66-e24f6cd678e7)
Openpose
![what_openpose_see](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/16047777/7b33cc8b-6a50-4323-aa0b-ab5fd7d01177)

Result from DWPose
![ComfyUI_temp_mkxeb_00001_](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/16047777/42a24767-ff3d-4e22-bdbb-62fe995d1ff0)
Result from Openpose
![ComfyUI_temp_qcjag_00001_](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/16047777/773760ee-ea42-4ad9-880d-d87f7f12e352)

It is clear that the problem is irrelevant. The cause is just how imprecise Openpose is compared to DWPose.

**Comment by mav-rik** [comment]
I don't know what happened, but since now I am getting this error:
![Screenshot 2023-09-16 171832](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/20143759/7aad6e86-3dad-42df-9286-68bbaa235627)

**Comment by Eagle07-Sudo** [comment]
Same for "Fake Scribble Lines"

> I don't know what happened, but since now I am getting this error: ![Screenshot 2023-09-16 171832](https://user-images.githubusercontent.com/20143759/268455959-7aad6e86-3dad-42df-9286-68bbaa235627.png)

**Comment by hanli2016** [comment]
> Fixed at [171a4a4](https://github.com/Fannovel16/comfyui_controlnet_aux/commit/171a4a46010aa47856b5a452eccd20054226b2e6) and [825f7c6](https://github.com/Fannovel16/comfyui_controlnet_aux/commit/825f7c6cba4d3f76d1706d72a0db99607ace8a27)
> 
> I'm hoping that upgrading protobuf won't create conflicts.

I can use mediapipe by using protobuf==3.20.3，someone can test it.
