### ISSUE TITLE
Where's the model? md didn't say either

### ISSUE THREAD

**Issue by nigelfxxk** [Fannovel16/comfyui_controlnet_aux#450]
Where's the model? md didn't say either

**Comment by Fannovel16** [comment]
@nigelfxxk It's downloaded automatically

**Comment by sava11** [comment]
under what circumstances? where is it written?
I have a problem. When using it, an error appears.
![image](https://github.com/user-attachments/assets/a9872206-e214-443f-98f8-c5eb485b459a)
