### ISSUE TITLE
3 Conflicting Nodes (AnimalPosePreprocessor, DWPreprocessor, DensePosePreprocessor)

### ISSUE THREAD

**Issue by GobbleCrow** [Fannovel16/comfyui_controlnet_aux#467]
As of 10/8/2024, when installing the package, these three preprocessors run this warning in the custom node manager panel. I updated everything, deleted and reinstalled the package, and it still throws this error. I really want to use these (especially DWPreprocessor) , so any help would be greatly appreciated. Thanks!

【ComfyUI's ControlNet Auxiliary Preprocessors】Conflicted Nodes (3)
       AnimalPosePreprocessor [ComfyUI-tbox]
       DWPreprocessor [ComfyUI-tbox]
       DensePosePreprocessor [ComfyUI-tbox]

**Comment by changeyi111111** [comment]
Hello, have you solved it? I have the same problem with you. I look forward to answering it

**Comment by GobbleCrow** [comment]
I believe the issue was the file path was too long, if you’re on Windows
this is a known issue. Try moving the ComfyUI portable folder to your C
Drive and rename it “C” and then run it. It should work then.
