### ISSUE TITLE
Workflow Debug: Inconsistent Problems with "Dimension 1 Mismatch" /64 error. 

### ISSUE THREAD

**Issue by aegis72** [Fannovel16/comfyui_controlnet_aux#47]
First off, thanks for your excellent nodes!

Rather than retyoing the issue, I first was trying to figure this out in ComfyAnon's discussions  over there: 

**https://github.com/comfyanonymous/ComfyUI/discussions/1524**

I'm using the "Anime Lineart" preprocessor node to generate lines for the softedge controlnet. It works well when it works, but other times it doesn't and I can't figure out why. I know that the "dimension mismatch" is typically a thing where the input image dimensions aren't divisible by 64. I also have another workflow that used P2LDGan, which required images to be sub-1024, so I am doing that here as well.

I thought at first my math was wrong, but it seems to do the right calculations and resizes to those 64-divisible dimensions, so I am not sure what else might be the issue. I also thought that when it did work, that the reason was because the images were ALREADY conformant to what "Anime Lineart" needed, but then I note that the She-Hulk image I drew (which is natively not divisible by 64) processes as expected.

What am I missing?

**Comment by Fannovel16** [comment]
Did you pull the latest commit? I fixed the bug at https://github.com/Fannovel16/comfyui_controlnet_aux/commit/171a4a46010aa47856b5a452eccd20054226b2e6

**Comment by Fannovel16** [comment]
Also, can you send the image triggering the error?

**Comment by aegis72** [comment]
Maybe not? I try to do Updates via the ComfyManager, but I will manually do it now and see if that fixes things. Are you saying that I can avoid the resizing stuff altogether? Would you personally still size it to <=1024 anyway for performance?

**Comment by aegis72** [comment]
Thanks; should be able to test within the hour. crazy day so far

**Comment by aegis72** [comment]
OK, so for testing I made two dirt simple workflows. I am NOT an amazing Git-Jockey, so I may have done the update incorrectly here, so that's probably the first thing I could have done wrong.

[test_of_Anime_Lineart+test_images.zip](https://github.com/Fannovel16/comfyui_controlnet_aux/files/12622930/test_of_Anime_Lineart%2Btest_images.zip)

I've included text from startup process, the execution error, and my update process.

![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/118572301/c65d8528-fa7c-4738-bc19-3ccbd914552b)


Otherwise, there isn't much happening in this WF; load image, try to run through the Preprocessor, then Preview.
This is a view of the extensions installed related to "controlnet" in the manager. 
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/118572301/f68e20f7-fa01-477e-8ddb-9b0f3f0b57e9)
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/118572301/88684d7f-5e70-4014-9d16-5422e0141d23)

**Comment by aegis72** [comment]
I am uninstalling via the Manager and re-installing the Aux Preprocessors to be sure I've got the latest

**Comment by aegis72** [comment]
When in doubt, re-install everything!
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/118572301/f3d4adc8-3a4a-4021-8847-1d40c1c8597d)

**Comment by aegis72** [comment]
Thanks for the assist...also glad to not need all that extra fluff math now!

**Comment by aegis72** [comment]
Thanks for the assist...also glad to not need all that extra fluff math now!

**Comment by aegis72** [comment]
Integrated again :) 
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/118572301/20a8bb78-68ff-4e6d-a84e-8e249a1594ee)
