### ISSUE TITLE
Hello I was reading a description mentioning one of your repos, where is "https://github.com/Fannovel16/comfy_controlnet_preprocessors"?

### ISSUE THREAD

**Issue by ClothingAI** [Fannovel16/comfyui_controlnet_aux#472]
Hello I was reading a description mentioning one of your repos, where is "https://github.com/Fannovel16/comfy_controlnet_preprocessors"

Thanks.
Did I miss something?

**Comment by Fannovel16** [comment]
It was deprecated and removed

**Comment by ClothingAI** [comment]
> It was deprecated and removed

@Fannovel16  actually you should have kept it and put a message "This is no longer viable, go to .. insert new url", 
Question you ask me: why?
Because there are TONS of people still linking to that repo:
one example:
https://www.youtube.com/watch?v=DvUSGpJIZnc
Look the pinned comment from the youtuber, he is linking to the repo that you said is "deprecated and removed".
How people would know? All the new people exploring comfy and learning though youtuber videos like these.
