### ISSUE TITLE
ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly   warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")

### ISSUE THREAD

**Issue by stromyu520** [Fannovel16/comfyui_controlnet_aux#486]
D:\AI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-14 14:54:22.560998
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: D:\AI\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: D:\AI\ComfyUI_windows_portable\ComfyUI
** Log path: D:\AI\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   1.8 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8188 MB, total RAM 32469 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\AI\ComfyUI_windows_portable\ComfyUI\web
Adding extra search path checkpoints E:\dev\pythonProject\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path configs E:\dev\pythonProject\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae E:\dev\pythonProject\stable-diffusion-webui\models/VAE
Adding extra search path loras E:\dev\pythonProject\stable-diffusion-webui\models/Lora
Adding extra search path loras E:\dev\pythonProject\stable-diffusion-webui\models/LyCORIS
Adding extra search path upscale_models E:\dev\pythonProject\stable-diffusion-webui\models/ESRGAN
Adding extra search path upscale_models E:\dev\pythonProject\stable-diffusion-webui\models/RealESRGAN
Adding extra search path upscale_models E:\dev\pythonProject\stable-diffusion-webui\models/SwinIR
Adding extra search path embeddings E:\dev\pythonProject\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks E:\dev\pythonProject\stable-diffusion-webui\models/hypernetworks
Adding extra search path controlnet E:\dev\pythonProject\stable-diffusion-webui\models/ControlNet
D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
[Crystools INFO] Crystools version: 1.21.0
[Crystools INFO] CPU: 13th Gen Intel(R) Core(TM) i7-13700H - Arch: AMD64 - OS: Windows 11
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4060 Laptop GPU
[Crystools INFO] NVIDIA Driver: 565.90
### ComfyUI Revision: 2812 [5e29e7a4] | Released on '2024-11-06'
[comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")

**Comment by emogie** [comment]
try

pip install onnxruntime-gpu

**Comment by stromyu520** [comment]
> @stromyu520如果您不熟悉在 ComfyUI 便携式中安装软件包：
> 
> 首先，您需要在主文件夹（`run_nvidia_gpu.bat`位于其中）内打开终端，然后使用此命令行安装 onnxruntime-gpu：
> 
> ```
> python_embeded\python.exe -m pip install onnxruntime-gpu
> ```




D:\AI\ComfyUI_windows_portable>pip install onnxruntime-gpu
Requirement already satisfied: onnxruntime-gpu in d:\program files\python3106\lib\site-packages (1.20.0)
Requirement already satisfied: coloredlogs in d:\program files\python3106\lib\site-packages (from onnxruntime-gpu) (15.0.1)
Requirement already satisfied: flatbuffers in d:\program files\python3106\lib\site-packages (from onnxruntime-gpu) (24.3.25)
Requirement already satisfied: numpy>=1.21.6 in d:\program files\python3106\lib\site-packages (from onnxruntime-gpu) (1.26.3)
Requirement already satisfied: packaging in d:\program files\python3106\lib\site-packages (from onnxruntime-gpu) (24.1)
Requirement already satisfied: protobuf in d:\program files\python3106\lib\site-packages (from onnxruntime-gpu) (4.25.5)
Requirement already satisfied: sympy in d:\program files\python3106\lib\site-packages (from onnxruntime-gpu) (1.13.1)
Requirement already satisfied: humanfriendly>=9.1 in d:\program files\python3106\lib\site-packages (from coloredlogs->onnxruntime-gpu) (10.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\program files\python3106\lib\site-packages (from sympy->onnxruntime-gpu) (1.3.0)
Requirement already satisfied: pyreadline3 in d:\program files\python3106\lib\site-packages (from humanfriendly>=9.1->coloredlogs->onnxruntime-gpu) (3.5.4)

D:\AI\ComfyUI_windows_portable>


The problem still exists

**Comment by stromyu520** [comment]
> @stromyu520如果您不熟悉在 ComfyUI 便携式中安装软件包：
> 
> 首先，您需要在主文件夹（`run_nvidia_gpu.bat`位于其中）内打开终端，然后使用此命令行安装 onnxruntime-gpu：
> 
> ```
> python_embeded\python.exe -m pip install onnxruntime-gpu
> ```


python_embeded\python.exe环境 和 D:/python环境 。如果ComfyUI使用python_embeded\python.exe环境，我之前的pip install onnxruntime-gpu安装后错误依然才。

感谢你的帮助
