### ISSUE TITLE
Repository Not Found: Depth-Anything-V2-Giant

### ISSUE THREAD

**Issue by LukeG89** [Fannovel16/comfyui_controlnet_aux#487]
When selecting `depth_anything_v2_vitg.pth` in `Depth Anything V2 - Relative` node, this error occurs:

```powershell
Repository Not Found for url: https://huggingface.co/depth-anything/Depth-Anything-V2-Giant/resolve/main/depth_anything_v2_vitg.pth.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
```

I tried manually searching the repo, but it seems that Giant has been removed: https://huggingface.co/depth-anything/Depth-Anything-V2-Giant

![depth](https://github.com/user-attachments/assets/ef74e200-8687-4eee-8936-a885fab621e2)

**Comment by emogie** [comment]
<html><body>

Depth-Anything-V2-Giant | 1.3B | Coming soon
-- | -- | --



</body>
</html>

source: https://github.com/DepthAnything/Depth-Anything-V2

**Comment by LukeG89** [comment]
> Depth-Anything-V2-Giant | 1.3B | Coming soon -- | -- | --
> source: https://github.com/DepthAnything/Depth-Anything-V2

As I can see, Giant has been removed on June 14: https://github.com/DepthAnything/Depth-Anything-V2/commit/0a7e2b58a7e378c7863bd7486afc659c41f9ef99

**Comment by Fannovel16** [comment]
@LukeG89 I'll remove giant from the code but imo giant is not much better than large

**Comment by a63976659** [comment]
> [@LukeG89](https://github.com/LukeG89)我会从代码中移除giant，但在我看来，它并没有比large好多少，尽管它有两倍的参数，特别是在与ControlNet结合使用时。

When should it be removed from the code? The default first option can be very confusing
