### ISSUE TITLE
 SD1.5 version of controlnet reported an error when loading the model.What should I do?

### ISSUE THREAD

**Issue by nno-magic** [Fannovel16/comfyui_controlnet_aux#50]
error code：Error occurred when executing ControlNetLoader: module 'comfy.sd' has no attribute 'ModelPatcher' File "E:\comonAI\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) File "E:\comonAI\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) File "E:\comonAI\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) File "E:\comonAI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 602, in load_controlnet controlnet = comfy.controlnet.load_controlnet(controlnet_path) File "E:\comonAI\ComfyUI_windows_portable\ComfyUI\comfy\controlnet.py", line 394, in load_controlnet control = ControlNet(control_model, global_average_pooling=global_average_pooling) File "E:\comonAI\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIT\AITemplate\AITemplate.py", line 347, in init self.control_model_wrapped = comfy.sd.ModelPatcher(self.control_model, load_device=comfy.model_management.get_torch_device(), offload_device=comfy.model_management.unet_offload_device())

**Comment by Fannovel16** [comment]
Try update both ComfyUI and AIT extension to the latest version.

The bug you mentioned is related to AIT extension, not Aux extension so this issue will be closed. If it still remains, create a new one at https://github.com/FizzleDorf/AIT/issues
