### ISSUE TITLE
Openpose Face/Hands no longer detecting

### ISSUE THREAD

**Issue by VikingTechLLC** [Fannovel16/comfyui_controlnet_aux#54]
From the prior repo they work just fine
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/84103587/ac2137a9-83be-4377-9f37-2fe4aedabd82)

And from the new repo (this one), they don't seem to detect at all.  Tried several images
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/84103587/a95c6cc4-f459-43c9-b9e5-d7dc935963a9)
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/84103587/a3fab0b7-f8ec-457a-b89a-4f9c2f6b6e4f)
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/84103587/84043028-a9ee-4b86-b4a2-277e6204ebf9)

**Comment by tobias-dv-lnu** [comment]
Same here, body working in this version, but not hand and face. All working in version from old repo.

**Comment by jamiespaceape** [comment]
I found the issue - in the __init__.py in src/controlnet_aux/dwpose it needs to have the include_hand and include_face bool
` def detect_poses(self, oriImg, include_hand=False, include_face=False) -> List[PoseResult]:
`
and
`        poses = self.detect_poses(detected_map,input_image, include_hand, include_face)
`

**Comment by TheMasterFX** [comment]
> I found the issue - in the **init**.py in src/controlnet_aux/dwpose it needs to have the include_hand and include_face bool `def detect_poses(self, oriImg, include_hand=False, include_face=False) -> List[PoseResult]:` and ` poses = self.detect_poses(detected_map,input_image, include_hand, include_face)`

Does't work with my installation. Change it and cleared pycache but still no face detection. Commit ff5648559d54b66a6b47caeb5203a1bf8e26a90e

**Comment by TheMasterFX** [comment]
Anything new on this? Still not working :-(

**Comment by VikingTechLLC** [comment]
Not that I've seen unfortunately

**Comment by taconugget** [comment]
Doens't work on my end either.
Im running Ubuntu 22.04 LTS w/ NVIDIA-SMI 530.30.02 - Driver Version: 530.30.02 - CUDA Version: 12.1
ComfyUI Revision: 1697

**Comment by somebush** [comment]
> > I found the issue - in the **init**.py in src/controlnet_aux/dwpose it needs to have the include_hand and include_face bool `def detect_poses(self, oriImg, include_hand=False, include_face=False) -> List[PoseResult]:` and ` poses = self.detect_poses(detected_map,input_image, include_hand, include_face)`
> 
> Does't work with my installation. I changed it and cleared pycache but still no face detection. Commit [ff56485](https://github.com/Fannovel16/comfyui_controlnet_aux/commit/ff5648559d54b66a6b47caeb5203a1bf8e26a90e)
> 
> I just went back to [4c81504](https://github.com/Fannovel16/comfyui_controlnet_aux/commit/4c815047b7c4d1cd6021dbca869c093f21ad2c1e) and now it seems to work

How to install the old version? There is only new one in Manager.

**Comment by somebush** [comment]
> `def detect_poses(self, oriImg, include_hand=False, include_face=False) -> List[PoseResult]:`
> and
> ` poses = self.detect_poses(detected_map,input_image, include_hand, include_face)`

it didn't work for me. I tried to edit the file with controlnet_aux already installed, and I also tried to edit the file before I installed it.

**Comment by Fannovel16** [comment]
Just pushed the fix. It should work if yall update this extension

**Comment by TheMasterFX** [comment]
Looks good. Thank you @Fannovel16 
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/12451336/b088ff46-1087-40be-a1d2-292dad819365)

**Comment by taconugget** [comment]
Thanks for the FIX!
