### ISSUE TITLE
Merge opportunity

### ISSUE THREAD

**Issue by mlinmg** [Fannovel16/comfyui_controlnet_aux#55]
I have implemented the LaMa preprocessor from inapint_only+lama preprocessor from Automatic1111. 
Please help me finish the implementation of LaMa Processor in my [repo]("https://github.com/mlinmg/ComfyUI-LaMA-Preprocessor/tree/main"). I'm missing some final step on how to use the generated image as an efficent control. It seems it either gives too much control or too little.
When the preprocessor will be ready I could merge it to this repo to finally achieve prompless in and out painting in comfy

**Comment by amimi818** [comment]
Did you implement inapint_only+lama preprocessor in comfyui?

**Comment by mlinmg** [comment]
Yes, check it on my profile
