### ISSUE TITLE
Workflow for the "RAFT Optical Flow Embedder" node

### ISSUE THREAD

**Issue by hben35096** [Fannovel16/comfyui_controlnet_aux#57]
Looks like an interesting node, but don't know how to use it.

**Comment by youcanyoubing** [comment]
https://github.com/Fannovel16/comfyui_controlnet_aux/issues/58

**Comment by Fannovel16** [comment]
`RAFT Optical Flow Embedder` is removed as I misunderstood the logic behind TemporalNet2's code
