### ISSUE TITLE
 RAFT requires at least two images to work with, only found 1

### ISSUE THREAD

**Issue by Yorha4D** [Fannovel16/comfyui_controlnet_aux#58]
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/116185401/81912ec3-4760-4070-a11b-9728c62b0812)
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/116185401/03d4bb7d-bb7c-49a7-8f47-27fa36280992)
@Fannovel16

**Comment by Fannovel16** [comment]
RAFT is an optical flow estimation model so it needs at least two images in one image batch. You should put video frames into a folder then use `Load Images` from https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet to load all of them.

**Comment by MoonMoon82** [comment]
@Fannovel16 What do I have to do to make TemporalNet2 run properly?
I put the YAML and CKPT file into the controlnet model folder loaded some frames from a short videoclip into the Controlnet input, but it seems nothing special is happenening there. Just flickering between frames like without using the TemporalNet2 Controlnet.
![grafik](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/41437842/7561b6fa-0277-4251-9445-088bdb489933)
No error messages appear.

**Comment by Fannovel16** [comment]
@MoonMoon82 I realized that I had forgot to put normalization 😅 . Can you do a `git pull` and try again?

**Comment by MoonMoon82** [comment]
@Fannovel16 I really don't see any relevant difference using or not using temporalnet2. It's still flickering as hell. Maybe it's meant to flicker? It's a ~12GByte CKPT controlnet model file but in the result there isn't even noticable difference.. Am I'm expecting too much?

**Comment by youcanyoubing** [comment]
Hello, what kind of control network model do you use

**Comment by youcanyoubing** [comment]
> 我真的没有看到使用或不使用 temporalnet2 的任何相关区别。它仍然像地狱一样闪烁。也许它意味着闪烁？这是一个~12GByte CKPT控制网模型文件，但在结果中甚至没有明显的差异。我是不是期待太多了？

**Comment by youcanyoubing** [comment]
> 我该怎么做才能使 TemporalNet2 正常运行？我将 YAML 和 CKPT 文件放入控制网模型文件夹中，将短视频剪辑中的一些帧加载到 Controlnet 输入中，但似乎那里没有什么特别的事情发生。只是在帧之间闪烁，就像不使用TemporalNet2控制网一样。 ![grafik](https://user-images.githubusercontent.com/41437842/270997039-7561b6fa-0277-4251-9445-088bdb489933.png)不显示任何错误消息。

Hello, what kind of control network model do you use
