### ISSUE TITLE
What about lineart realistic?

### ISSUE THREAD

**Issue by lsycxyj** [Fannovel16/comfyui_controlnet_aux#59]

**Comment by Fannovel16** [comment]
That is `Normal Lineart`

**Comment by Fannovel16** [comment]
Renamed `Normal Lineart` to `Realistic Lineart` at https://github.com/Fannovel16/comfyui_controlnet_aux/commit/532ed8c695cb661060baf302715f497b70c01fba

**Comment by lsycxyj** [comment]
But why are the result between webui and comfyui different when I tried to use lineart with the same weight (or strength), which is extracted from the same anime image? The result of webui will be better than comfyui. There are more details and the color is more natural. What are the diferences of the workflows?
