### ISSUE TITLE
warnings.warn("Currently DWPose doesn't support CUDA out-of-the-box.")

### ISSUE THREAD

**Issue by C0nsumption** [Fannovel16/comfyui_controlnet_aux#61]
Tried with DWpose, works but takes long to preprocess the images. I get this warning when it tries:

ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\__init__.py:175: UserWarning: Currently DWPose doesn't support CUDA out-of-the-box.

warnings.warn("Currently DWPose doesn't support CUDA out-of-the-box.")

Any thoughts? Why isn't it using the GPU out of the box? How do I set it up????

**Comment by roop03988** [comment]
To add to this, when I use DWPose, it is crashing my comfyui instance:

/media/ian/My Book/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/dwpose/__init__.py:175: UserWarning: Currently DWPose doesn't support CUDA out-of-the-box.
  warnings.warn("Currently DWPose doesn't support CUDA out-of-the-box.")
malloc(): invalid size (unsorted)
Aborted (core dumped)

**Comment by Fannovel16** [comment]
@roop03988 Try reinstalling opencv:
```
pip uninstall -y opencv-python opencv-contrib-python opencv-python-headless
pip install opencv-python==4.7.0.72
```

**Comment by roop03988** [comment]
> @roop03988 Try reinstalling opencv:
> 
> ```
> pip uninstall -y opencv-python opencv-contrib-python opencv-python-headless
> pip install opencv-python==4.7.0.72
> ```

Oh there it is, it worked (though I had to do pip install -U -r requirements.txt in the controlnet aux folder. 

However, the dependencies are now conflicting with was and rembg: 

   0.0 seconds (IMPORT FAILED): /media/ian/My Book/ComfyUI/custom_nodes/was-node-suite-comfyui
   0.0 seconds (IMPORT FAILED): /media/ian/My Book/ComfyUI/custom_nodes/rembg-comfyui-node

**Comment by Fannovel16** [comment]
@roop03988 Try reinstalling them 🤔

**Comment by roop03988** [comment]
> @roop03988 Try reinstalling them 🤔

yep this worked! but only if I reinstall -U requirements.txt first on rembg and was, then install -U requirements.txt on controlnet_aux last, thanks!
