### ISSUE TITLE
Is there equivalent to "my prompt/controlnet is more important"?

### ISSUE THREAD

**Issue by Rkkss** [Fannovel16/comfyui_controlnet_aux#66]
As in webui. How do we do it in comfyUI?

**Comment by Fannovel16** [comment]
The equivalent of  _My prompt is more important_  is Scaled Soft ControlNet in https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/. _ControlNet is more important isn't implemented as it does some wacky stuffs, according to the author of that custom node
