### ISSUE TITLE
Realistic Lineart throwing error

### ISSUE THREAD

**Issue by alenknight** [Fannovel16/comfyui_controlnet_aux#80]
when i use the realistic lineart preprocessor, i'm getting a "bad prompt" error and the command terminal saying that there's a missing image.  i've tried recreating the nodes, no luck.

```
Prompt executed in 0.12 seconds
got prompt
ERROR:root:Failed to validate prompt for output 48:
ERROR:root:* (prompt):
ERROR:root:  - Required input is missing: images
ERROR:root:* PreviewImage 48:
ERROR:root:  - Required input is missing: images
ERROR:root:Output will be ignored
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\lineart.py", line 19, in execute
    model = LineartDetector.from_pretrained(HF_MODEL_NAME, cache_dir=annotator_ckpts_path).to(model_management.get_torch_device())
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\lineart\__init__.py", line 112, in from_pretrained
    model.load_state_dict(torch.load(model_path, map_location=torch.device('cpu')))
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

Prompt executed in 0.14 seconds
got prompt
ERROR:root:Failed to validate prompt for output 48:
ERROR:root:* (prompt):
ERROR:root:  - Required input is missing: images
ERROR:root:* PreviewImage 48:
ERROR:root:  - Required input is missing: images
ERROR:root:Output will be ignored
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\lineart.py", line 19, in execute
    model = LineartDetector.from_pretrained(HF_MODEL_NAME, cache_dir=annotator_ckpts_path).to(model_management.get_torch_device())
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\lineart\__init__.py", line 112, in from_pretrained
    model.load_state_dict(torch.load(model_path, map_location=torch.device('cpu')))
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

Prompt executed in 0.10 seconds
```
Screenshot 2023-10-19 at 2.03.41 AM

the anime lineart one seems to work.

**Comment by alenknight** [comment]
<img width="801" alt="Screenshot 2023-10-19 at 2 03 41 AM" src="https://github.com/Fannovel16/comfyui_controlnet_aux/assets/22153900/0f1deb14-d186-4dd4-91cd-645172ab4f23">

**Comment by Fannovel16** [comment]
@alenknight The ckpt for `Realistic Lineart` preprocessor in your machine is corrupted. Do these steps to delete it
1. Go to `comfyui_controlnet_aux\ckpts\models--lllyasviel--Annotators\snapshots\982e7edaec38759d914a963c48c4726685de7d96\sk_model.pth`
2. Right click on that file, Open file location. It will redirect you to a 17MB file
3. Delete it and that file

Or you can just replace ckpts folder with an empty one.

**Comment by alenknight** [comment]
> @alenknight The ckpt for `Realistic Lineart` preprocessor in your machine is corrupted. Do these steps to delete it
> 
> 1. Go to `comfyui_controlnet_aux\ckpts\models--lllyasviel--Annotators\snapshots\982e7edaec38759d914a963c48c4726685de7d96\sk_model.pth`
> 2. Right click on that file, Open file location. It will redirect you to a 17MB file
> 3. Delete it and that file
> 
> Or you can just replace ckpts folder with an empty one.

Thanks. I’ll give it a shot shortly. Was thinking to test on another machine if it’s the specific file. Greatly appreciate your insight. 

How can you tell it’s corrupt? Was this a recent issue or am I missing something obvious in the error?

**Comment by alenknight** [comment]
yep that solved it :) thanks!

**Comment by vithii** [comment]
> > @alenknight The ckpt for `Realistic Lineart` preprocessor in your machine is corrupted. Do these steps to delete it
> > 
> > 1. Go to `comfyui_controlnet_aux\ckpts\models--lllyasviel--Annotators\snapshots\982e7edaec38759d914a963c48c4726685de7d96\sk_model.pth`
> > 2. Right click on that file, Open file location. It will redirect you to a 17MB file
> > 3. Delete it and that file
> > 
> > Or you can just replace ckpts folder with an empty one.
> 
> Thanks. I’ll give it a shot shortly. Was thinking to test on another machine if it’s the specific file. Greatly appreciate your insight.
> 
> How can you tell it’s corrupt? Was this a recent issue or am I missing something obvious in the error?

hey i don't have any files in that folder. still i got this error
![image](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/79393337/b0ac0991-623e-4baa-b51b-6b74ad66853d)

**Comment by urielkdev** [comment]
@vithii me neither, could you fix it?
