### ISSUE TITLE
Unsuitable ONNX_PROVIDERS when GPU support TensorRT

### ISSUE THREAD

**Issue by Layer-norm** [Fannovel16/comfyui_controlnet_aux#82]
I have installed TensorRT in my enviroment. And when I call function `ort.get_available_providers()`, it will return a List:
`['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'AzureExecutionProvider', 'CPUExecutionProvider']`

However, the first provider **'TensorrtExecutionProvider'** from TensorRT not native suport INT64 model such as **yolox_l.onnx** and **dw-ll_ucoco_384.onnx**. If you use INT64 ONNX Model in my enviroment with function like `ort_session_pose = ort.InferenceSession(onnx_pose, providers=ort.get_available_providers())`, you probobaly get less precision and be warned like this:
` [W:onnxruntime:Default, tensorrt_execution_provider.h:77 log] [2023-10-20 10:37:57 WARNING] onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.`

But, all I needed is JUST TWO providers, **'CUDAExecutionProvider'** and **'CPUExecutionProvider'**. 
Here are my solution, I changed something in ./src/controlnet_aux/dwpose/wholebody.py
```
# line 10 in /src/controlnet_aux/dwpose/wholebody.py
ONNX_PROVIDERS = ["CUDAExecutionProvider", "DirectMLExecutionProvider", "OpenVINOExecutionProvider", "ROCMExecutionProvider"]
SUPPORT_PROVIDERS = []
def check_ort_gpu():
    try:
        import onnxruntime as ort
        for provider in ONNX_PROVIDERS:
            if provider in ort.get_available_providers():
                SUPPORT_PROVIDERS.append(provider)
                return True
        return False
    except:
        return False

#Global caching as the startup of onnxruntime is a bit slow
ort_session_det, ort_session_pose = None, None

class Wholebody:
    def __init__(self, onnx_det: str, onnx_pose: str):
        global ort_session_det, ort_session_pose
        if check_ort_gpu():
            import onnxruntime as ort
            if ort_session_det is None:
                SUPPORT_PROVIDERS.append('CPUExecutionProvider')
                ort_session_det = ort.InferenceSession(onnx_det, providers=SUPPORT_PROVIDERS)
                ort_session_pose = ort.InferenceSession(onnx_pose, providers=SUPPORT_PROVIDERS)
            self.session_det = ort_session_det
            self.session_pose = ort_session_pose
            return
```
It works and warning no longer appears.

**Comment by time9517** [comment]
When loading the graph, the following node types were not found:
DW姿态预处理器
Nodes that have failed to load will show as red on the graph.
