### ISSUE TITLE
DWPreprocessor extremely slow (i9 RTX4090)

### ISSUE THREAD

**Issue by yht0** [Fannovel16/comfyui_controlnet_aux#86]
it does come up with great result but it's extremely slow. Not sure if it is processed on GPU. Is it normally a slow process or something is wrong on my end? there's no error message on the command prompt and things do run smooth after the DWPreprocessor. Will it help if i lower the resolution of the node?

**Comment by Fannovel16** [comment]
@yht0 Yes, that is expected if you don't have onnxruntime. The problem with DWPose is that it can only run on CPU unless you build OpenCV with CUDA support or install onnxruntime-gpu. I choose to not support the former as ppl will flood the Issue tab with "OpenCV dependencies hell" 😅. You can follow the instruction in https://github.com/Fannovel16/comfyui_controlnet_aux#qa but you will need to downgrade your ComfyUI to cu118 first

**Comment by Fannovel16** [comment]
If you don't want to install it, you can also lower the resolution

**Comment by yht0** [comment]
totally understood! thank you so much I'll see what happens by first lowering the resolution to 256. If things don't work out, I don't see a harm in downgrading to cu118.
