### ISSUE TITLE
Can't install preprocessors: AttributeError: module 'cv2.gapi.wip.draw' has no attribute 'Text'

### ISSUE THREAD

**Issue by Lokrer** [Fannovel16/comfyui_controlnet_aux#88]
Hi everyone, 

when I start comfyUI, running on Mac, terminal always gives me this error message: 

AttributeError: module 'cv2.gapi.wip.draw' has no attribute 'Text'

Cannot import /Users/lucasadrian/ComfyUI/custom_nodes/comfyui_controlnet_aux module for custom nodes: module 'cv2.gapi.wip.draw' has no attribute 'Text'

The nodes consequently don't show up in Comfy. 

Does anyone know how to fix this? Help would be greatly appreciated!

Lokrer

**Comment by Fannovel16** [comment]
The cause is cv2 dependencies conflict. You can fix it by running commands mentioned in https://github.com/Fannovel16/comfyui_controlnet_aux/issues/60#issuecomment-1735726142

Note that if you are usinf Confy portable, you must run:
```
path-to-ComfyUI-portable\python_embeded\python -s -m pip ...
```

**Comment by Lokrer** [comment]
Thank you so much, this worked!

**Comment by anagilabs** [comment]
**Hi, I got the same error, tried the steps as suggested:** 

PS C:\Users\us\comfyui\ComfyUI_windows_portable> python_embeded\python -s -m pip uninstall -y opencv-python opencv-contrib-python opencv-python-headless
Found existing installation: opencv-python 4.7.0.72
Uninstalling opencv-python-4.7.0.72:
  Successfully uninstalled opencv-python-4.7.0.72
WARNING: Skipping opencv-contrib-python as it is not installed.
WARNING: Skipping opencv-python-headless as it is not installed.
PS C:\Users\us\comfyui\ComfyUI_windows_portable> python_embeded\python -s -m pip install opencv-python==4.7.0.72
Collecting opencv-python==4.7.0.72
  Using cached opencv_python-4.7.0.72-cp37-abi3-win_amd64.whl (38.2 MB)
Requirement already satisfied: numpy>=1.21.2 in c:\users\us\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from opencv-python==4.7.0.72) (1.26.1)
Installing collected packages: opencv-python
Successfully installed opencv-python-4.7.0.72
PS C:\Users\us\comfyui\ComfyUI_windows_portable>

**But still getting the same error:**

Device: cuda:0 NVIDIA GeForce RTX 3050 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Torch version: 2.1.0+cu121
Traceback (most recent call last):
  File "C:\Users\us\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\us\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 2, in <module>
    from .utils import here, create_node_input_types
  File "C:\Users\us\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 4, in <module>
    import cv2
  File "C:\Users\us\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\us\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\us\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "C:\Users\us\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\cv2\typing\__init__.py", line 157, in <module>
    Prim = typing.Union[cv2.gapi.wip.draw.Text, cv2.gapi.wip.draw.Circle, cv2.gapi.wip.draw.Image, cv2.gapi.wip.draw.Line, cv2.gapi.wip.draw.Rect, cv2.gapi.wip.draw.Mosaic, cv2.gapi.wip.draw.Poly]
                        ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'cv2.gapi.wip.draw' has no attribute 'Text'

Cannot import C:\Users\us\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux module for custom nodes: module 'cv2.gapi.wip.draw' has no attribute 'Text'

can anyone help or suggest how to fix this issue, i see others had same problem and solved it, but not working for me..

**Comment by Iceisnice88** [comment]
![text](https://github.com/Fannovel16/comfyui_controlnet_aux/assets/156964098/f718969f-7498-4be1-96e9-4c0e5107a6d9)

tried every solution out there nothing seems to be working :(

**Comment by Kin-Zhang** [comment]
I solved through this comment: https://github.com/Fannovel16/comfyui_controlnet_aux/issues/60#issuecomment-1735726142

```bash
pip uninstall -y opencv-python opencv-contrib-python opencv-python-headless 
pip install opencv-python==4.7.0.72
```
