### ISSUE TITLE
Long loading time issue, related to dwpose, after installing the proper onnxruntime-gpu.

### ISSUE THREAD

**Issue by ltdrdata** [Fannovel16/comfyui_controlnet_aux#89]
To resolve the issue of DWPose running on CPU, I installed the `onnxruntime-gpu` package. However, I've discovered that in ComfyUI, there is a phenomenon where this code is executed for about 10 seconds every time cnet aux is imported.

https://github.com/Fannovel16/comfyui_controlnet_aux/blob/d67fe4c44e5b035ed68ed0d481b8b0ebf4bad41f/node_wrappers/dwpose.py#L20

Is there a specific reason why this check code needs to be placed in the startup?

**Comment by Fannovel16** [comment]
@ltdrdata Onnxruntime session creation is very long compared to other preprocessor models, which can affect the performance of DWPose as they are not cached by Comfy cache mechanism. Therefore, it is cached as a global variable.

But I forgot to make a flag checking whether the session is cached or not. Thanks for pointing it out.
