### ISSUE TITLE
【Requset】add new preprocesser

### ISSUE THREAD

**Issue by sdbds** [Fannovel16/comfyui_controlnet_aux#94]
https://github.com/Mikubill/sd-webui-controlnet/pull/2212

**Comment by Fannovel16** [comment]
@sdbds Added. The segmentation model for anime face can't make the right background mask in many cases so I added SkyTNT's character segmentation model to remove the background for it, thus improves the accurency
![](https://raw.githubusercontent.com/Fannovel16/comfyui_controlnet_aux/main/example_anime_face_segmentor.png)

**Comment by sdbds** [comment]
> @sdbds Added. The segmentation model for anime face is struggle with recognizing the background in many cases so I added SkyTNT's [character segmentation model](https://github.com/SkyTNT/anime-segmentation) to remove the background beforehand, thus improves the accurency ![](https://raw.githubusercontent.com/Fannovel16/comfyui_controlnet_aux/main/example_anime_face_segmentor.png)

Thank you for your swift and excellent work! 
Your genius idea really improves the model preprocessing graph to a great extent. 
I will train another new version(V3) of the controlnet model based on your improvements, thanks again for your contribution!
